# database.yaml
entity: Database
columns:
  - name: attributes.name
    source: database_name
  - name: attributes.qualified_name
    source: concat(connection_qualified_name, '/', database_name)
    source_columns: [connection_qualified_name, database_name]
  - name: attributes.connectionQualifiedName
    source: connection_qualified_name
  - name: attributes.connectionName
    source: connection_name
  - name: attributes.description
    source: comment
  - name: attributes.description
    source: remarks
  - name: attributes.schemaCount
    source: schema_count
  - name: attributes.source_created_by
    source: source_owner
  - name: attributes.source_created_at
    source: created
  - name: attributes.source_updated_at
    source: last_altered
  - name: attributes.source_id
    source: source_id
  - name: typeName
    source: "'Database'"