# database.yaml
table: Database
columns:
  - name: attributes.name
    source_query: database_name
  - name: attributes.qualified_name
    source_query: concat(connection_qualified_name, '/', database_name)
    source_columns: [connection_qualified_name, database_name]
  - name: attributes.connectionQualifiedName
    source_query: connection_qualified_name
  - name: attributes.connectionName
    source_query: connection_name
  - name: attributes.description
    source_query: comment
  - name: attributes.description
    source_query: remarks
  - name: attributes.schemaCount
    source_query: schema_count
  - name: attributes.source_created_by
    source_query: source_owner
  - name: attributes.source_created_at
    source_query: created
  - name: attributes.source_updated_at
    source_query: last_altered
  - name: attributes.source_id
    source_query: source_id
  - name: typeName
    source_query: "'Database'"