#!/usr/bin/env python3
"""Generate an app's ``api/`` package: the handler as the consolidated API host installs it.

The handler, and everything it imports from ``app/``, stays in ``app/`` and is
edited there. The host installs a small wheel that ships those same files under
a unique package name (``atlan_mysql_api``), on ``atlan-application-sdk-api``
instead of the worker SDK. This script writes that wheel's packaging from a few
lines in the app's root ``pyproject.toml`` and records it in ``api/``, so no
app hand-maintains it::

    [tool.atlan-app-api]
    handler = "app.handler:MySQLAppHandler"   # the Handler class the host serves
    data = ["app/sql/*.sql"]                  # non-Python files the handler reads
    dependencies = ["aiomysql>=0.3.0"]        # the handler's own third-party deps
    extras = ["sql", "aws"]                   # atlan-application-sdk-api extras

Generated (all marked do-not-edit):

* ``api/api-files.txt``: the handler module's closure inside ``app/``, plus
  ``data``;
* ``api/pyproject.toml``: the distribution, its deps and the ``atlan.app_api``
  entry point;
* ``api/hatch_build.py``: ships each listed ``app/<x>`` as ``<package>/<x>``;
* ``api/<package>/__init__.py``: exposes the handler instance.

The listed files must import each other **relatively** (``from .client import
SQLClient``). The same file is ``app.handler`` in the worker and
``<package>.handler`` on the host, and only a relative import works under both.
``--fix`` rewrites absolute ``from app...`` imports in listed files to relative
ones.

Usage, from the app repo root::

    python3 <sdk>/.github/scripts/gen_app_api.py           # write api/
    python3 <sdk>/.github/scripts/gen_app_api.py --fix     # also rewrite imports
    python3 <sdk>/.github/scripts/gen_app_api.py --check   # exit 1 if stale (CI)

A repo without ``[tool.atlan-app-api]`` is not using this layout: ``--check``
prints that and exits 0.
"""

from __future__ import annotations

import argparse
import ast
import glob
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

SECTION = "atlan-app-api"
APP = "app"
GENERATED = "GENERATED by application-sdk .github/scripts/gen_app_api.py from [tool.atlan-app-api] — do not edit; change the config and regenerate."

#: SDK imports whose usual path loads worker-only code, and the path handler
#: code uses instead (same object). ``--fix`` rewrites them in listed files.
KNOWN_MOVES = {
    "from application_sdk.execution.heartbeat import run_in_thread": (
        "from application_sdk.common.concurrency import run_in_thread"
    ),
}

_HOOK = '''"""{generated}

Ships the app/ files listed in api-files.txt as {package}/<path under app/>.
The sdist keeps them at app/... next to this file; a wheel built from the
unpacked sdist reads them there, and a wheel built in the repo reads them from
the repo root.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class AppFilesHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        here = Path(self.root).resolve()
        text = (here / "api-files.txt").read_text(encoding="utf-8")
        listed = [ln for ln in text.splitlines() if ln and not ln.startswith("#")]
        for rel in listed:
            source = here / rel if (here / rel).is_file() else here.parent / rel
            target = "{package}/" + rel.removeprefix("app/")
            if self.target_name == "sdist":
                target = rel
            build_data["force_include"][str(source)] = target
'''

_INIT = '''"""{generated}

The {name} app's handler as the consolidated API host installs it. The code
lives in app/ (see api-files.txt) and is edited there.
"""

from __future__ import annotations

from .{module} import {cls}

#: The instance the host serves (entry point ``atlan.app_api: {name}``).
handler = {cls}()

__all__ = ["{cls}", "handler"]
'''


@dataclass(frozen=True)
class Config:
    handler_module: str  # e.g. app.handler
    handler_class: str
    data: list[str]
    dependencies: list[str]
    extras: list[str]
    project: str  # root project name, e.g. atlan-mysql-app
    version: str
    sdk_spec: str  # the root's atlan-application-sdk specifier, e.g. >=3.40,<4
    api_source: dict | None  # root [tool.uv.sources] atlan-application-sdk-api

    @property
    def name(self) -> str:  # mysql
        return re.sub(r"^atlan-|-app$", "", self.project)

    @property
    def distribution(self) -> str:  # atlan-mysql-api
        return re.sub(r"-app$", "", self.project) + "-api"

    @property
    def package(self) -> str:  # atlan_mysql_api
        return self.distribution.replace("-", "_")


def load(root: Path) -> Config | None:
    data = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    section = data.get("tool", {}).get(SECTION)
    if section is None:
        return None
    module, _, cls = section["handler"].partition(":")
    if not module.startswith(APP + ".") or not cls:
        raise ValueError(f"[tool.{SECTION}].handler must be 'app.<module>:<Class>'")
    project = data["project"]
    sdk_spec = ""
    for dep in project.get("dependencies", []):
        match = re.match(r"atlan-application-sdk(\[[^\]]*\])?\s*(.*)$", dep)
        if match and not dep.startswith("atlan-application-sdk-"):
            sdk_spec = match.group(2).split(";")[0].strip()
    sources = data.get("tool", {}).get("uv", {}).get("sources", {})
    return Config(
        handler_module=module,
        handler_class=cls,
        data=list(section.get("data", [])),
        dependencies=list(section.get("dependencies", [])),
        extras=list(section.get("extras", [])),
        project=project["name"],
        version=project["version"],
        sdk_spec=sdk_spec,
        api_source=sources.get("atlan-application-sdk-api"),
    )


def _module_file(root: Path, module: str) -> str | None:
    base = module.replace(".", "/")
    for rel in (f"{base}.py", f"{base}/__init__.py"):
        if (root / rel).is_file():
            return rel
    return None


def _app_imports(
    tree: ast.Module, module: str
) -> list[tuple[ast.ImportFrom | ast.Import, str, bool]]:
    """``(node, imported app module, is_relative)`` for every app-internal import."""
    package = module.rpartition(".")[0]
    found = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.level:
                parts = package.split(".")
                parts = parts[: len(parts) - (node.level - 1)]
                base = ".".join([*parts, node.module] if node.module else parts)
                found.append((node, base, True))
                found.extend((node, f"{base}.{a.name}", True) for a in node.names)
            elif (node.module or "").split(".")[0] == APP:
                found.append((node, node.module or "", False))
                found.extend(
                    (node, f"{node.module}.{a.name}", False) for a in node.names
                )
        elif isinstance(node, ast.Import):
            found.extend(
                (node, a.name, False) for a in node.names if a.name.split(".")[0] == APP
            )
    return found


def closure(root: Path, config: Config) -> tuple[list[str], list[str]]:
    """The handler's files inside app/, and the absolute app imports among them."""
    files: set[str] = set()
    absolute: list[str] = []
    stack = [config.handler_module]
    while stack:
        module = stack.pop()
        rel = _module_file(root, module)
        if rel is None or rel in files:
            continue
        files.add(rel)
        tree = ast.parse((root / rel).read_text(encoding="utf-8"), filename=rel)
        for node, target, relative in _app_imports(tree, module):
            if _module_file(root, target) is None:
                continue  # a name inside a module
            if not relative:
                absolute.append(f"{rel}:{node.lineno}: absolute import of {target}")
            stack.append(target)
    for pattern in config.data:
        matches = sorted(glob.glob(pattern, root_dir=root))
        if not matches:
            raise ValueError(
                f"[tool.{SECTION}].data pattern {pattern!r} matches nothing"
            )
        files.update(matches)
    return sorted(files), sorted(set(absolute))


def fix_absolute_imports(root: Path, files: list[str]) -> list[str]:
    """Rewrite ``from app.x import y`` in listed files to relative imports, and
    apply :data:`KNOWN_MOVES`."""
    changed = []
    for rel in files:
        if not rel.endswith(".py"):
            continue
        path = root / rel
        text = path.read_text(encoding="utf-8")
        depth = len(Path(rel).parts) - 1  # app/handler.py → 1, app/a/b.py → 2

        def relative(match: re.Match[str]) -> str:
            target = match.group(2).split(".")
            here = list(Path(rel).parts[:-1])
            common = 0
            while (
                common < min(len(here), len(target)) and here[common] == target[common]
            ):
                common += 1
            dots = "." * (depth - common + 1)
            return f"{match.group(1)}from {dots}{'.'.join(target[common:])} import"

        new = re.sub(r"^(\s*)from (app(?:\.\w+)+) import", relative, text, flags=re.M)
        for old, replacement in KNOWN_MOVES.items():
            new = new.replace(old, replacement)
        if new != text:
            path.write_text(new, encoding="utf-8")
            changed.append(rel)
    return changed


def _api_requirement(config: Config) -> str:
    extras = f"[{','.join(config.extras)}]" if config.extras else ""
    source = config.api_source
    if source and "git" in source:
        ref = source.get("rev") or source.get("tag") or source.get("branch")
        sub = (
            f"#subdirectory={source['subdirectory']}"
            if source.get("subdirectory")
            else ""
        )
        return f"atlan-application-sdk-api{extras} @ git+{source['git']}@{ref}{sub}"
    return f"atlan-application-sdk-api{extras}{config.sdk_spec}"


def render(root: Path, config: Config) -> dict[str, str]:
    files, _ = closure(root, config)
    module = config.handler_module.removeprefix(APP + ".")
    deps = [_api_requirement(config), *config.dependencies]
    direct = config.api_source is not None and "git" in config.api_source
    pyproject = (
        f"# {GENERATED}\n\n"
        "[project]\n"
        f'name = "{config.distribution}"\n'
        f'version = "{config.version}"\n'
        f'description = "The {config.name} app\'s handler as the consolidated API host installs it"\n'
        'requires-python = ">=3.11"\n'
        "dependencies = [\n" + "".join(f'    "{d}",\n' for d in deps) + "]\n\n"
        '[project.entry-points."atlan.app_api"]\n'
        f'{config.name} = "{config.package}:handler"\n\n'
        "[build-system]\n"
        'requires = ["hatchling"]\n'
        'build-backend = "hatchling.build"\n\n'
        + (
            "[tool.hatch.metadata]\nallow-direct-references = true\n\n"
            if direct
            else ""
        )
        + "[tool.hatch.build.targets.wheel]\n"
        f'packages = ["{config.package}"]\n\n'
        "[tool.hatch.build.targets.wheel.hooks.custom]\n\n"
        "[tool.hatch.build.targets.sdist.hooks.custom]\n"
    )
    listing = f"# {GENERATED}\n" + "".join(f"{f}\n" for f in files)
    return {
        "api/pyproject.toml": pyproject,
        "api/api-files.txt": listing,
        "api/hatch_build.py": _HOOK.format(generated=GENERATED, package=config.package),
        f"api/{config.package}/__init__.py": _INIT.format(
            generated=GENERATED,
            name=config.name,
            module=module,
            cls=config.handler_class,
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path.cwd())
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if api/ is stale")
    mode.add_argument(
        "--fix", action="store_true", help="also make app imports relative"
    )
    args = parser.parse_args(argv)

    config = load(args.root)
    if config is None:
        print(
            f"gen_app_api: no [tool.{SECTION}] in pyproject.toml; nothing to generate"
        )
        return 0
    files, absolute = closure(args.root, config)
    if args.fix:
        for rel in fix_absolute_imports(args.root, files):
            print(f"gen_app_api: made app imports relative in {rel}")
        files, absolute = closure(args.root, config)
    problems = [
        f"{a} — listed files must import each other relatively (run with --fix)"
        for a in absolute
    ]
    for rel, want in render(args.root, config).items():
        path = args.root / rel
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have == want:
            continue
        if args.check:
            problems.append(
                f"{rel} is stale — run gen_app_api.py and commit the result"
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want, encoding="utf-8")
            print(f"gen_app_api: wrote {rel}")
    for problem in problems:
        print(f"::error::{problem}")
    if not problems:
        print(f"gen_app_api: api/ is current ({len(files)} files from app/)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
