#!/usr/bin/env python3
"""Generate ``packages/api/api-files.txt`` from the api distribution's seed modules.

``atlan-application-sdk-api`` ships a subset of ``application_sdk/``: the
modules listed as ``[tool.atlan-api.seeds]`` (grouped by extra) in ``packages/api/pyproject.toml``
plus everything they import. This computes that import closure and writes it,
so nobody hand-maintains the file list and it can never miss a dependency:

* every module-level ``application_sdk`` import is followed (outside
  ``if TYPE_CHECKING:``);
* a function-level import is followed too, unless it sits in a
  ``try``/``except ModuleNotFoundError`` — that is the marked fallback for
  worker-only code, which the api distribution deliberately omits;
* every parent package ``__init__.py`` of a listed module is listed.

``check_api_surface.py`` then checks the result (declared third-party deps,
guards with a stated fallback). Usage, from the repo root::

    python3 .github/scripts/gen_api_files.py          # rewrite api-files.txt
    python3 .github/scripts/gen_api_files.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import ast
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_api_surface as surface  # noqa: E402

HEADER = (
    "# Files of application_sdk/ shipped in atlan-application-sdk-api (paths from the repo root).\n"
    "# GENERATED by .github/scripts/gen_api_files.py from [tool.atlan-api.seeds] in\n"
    "# packages/api/pyproject.toml — do not edit; add a seed and regenerate.\n"
)


def seed_groups(root: Path) -> dict[str, list[str]]:
    """``{group: seed modules}``; ``core`` needs only the core dependencies,
    every other group is named after the extra that brings its deps."""
    data = tomllib.loads((root / surface.API_DIR / "pyproject.toml").read_text())
    groups = data["tool"]["atlan-api"]["seeds"]
    if "core" not in groups:
        raise ValueError("[tool.atlan-api.seeds] needs a core group")
    return {name: list(mods) for name, mods in groups.items()}


def seeds(root: Path) -> list[str]:
    return [m for mods in seed_groups(root).values() for m in mods]


def file_groups(root: Path) -> dict[str, set[str]]:
    """``{listed file: groups whose closure reaches it}`` (empty without seeds)."""
    data = tomllib.loads((root / surface.API_DIR / "pyproject.toml").read_text())
    if "atlan-api" not in data.get("tool", {}):
        return {}
    reached: dict[str, set[str]] = {}
    for group, mods in seed_groups(root).items():
        for rel in closure(root, mods):
            reached.setdefault(rel, set()).add(group)
    return reached


def closure(root: Path, start: list[str]) -> list[str]:
    """Every file the seed modules need on an api-only install."""
    found: set[str] = set()
    stack = list(start)
    while stack:
        module = stack.pop()
        rel = surface.file_of(root, module)
        if rel is None:
            if (root / module.replace(".", "/")).is_dir():
                continue  # a namespace directory (no __init__.py): nothing to ship
            raise ValueError(f"seed or import {module} does not exist")
        if rel in found:
            continue
        found.add(rel)
        parts = module.split(".")
        stack.extend(".".join(parts[:i]) for i in range(1, len(parts)))
        tree = ast.parse((root / rel).read_text(encoding="utf-8"), filename=rel)
        for _node, name, top, guarded, _required in surface._imports(  # noqa: SLF001
            tree, module, rel.endswith("__init__.py")
        ):
            if not name.startswith("application_sdk"):
                continue
            if surface.file_of(root, name) is None:
                continue  # a name inside a module, not a module
            if top or not guarded:
                stack.append(name)
    return sorted(found)


def render(root: Path) -> str:
    return HEADER + "".join(f"{rel}\n" for rel in closure(root, seeds(root)))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    path = args.root / surface.LIST_FILE
    want = render(args.root)
    have = path.read_text(encoding="utf-8") if path.exists() else ""
    if have == want:
        print(f"gen_api_files: {path} is current")
        return 0
    if args.check:
        print(
            f"::error::{path} is stale — run python3 .github/scripts/gen_api_files.py"
        )
        return 1
    path.write_text(want, encoding="utf-8")
    print(f"gen_api_files: wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
