#!/usr/bin/env python3
"""Renovate driver: regenerate contract_schema.lock.json at the newly locked
conformance version.

Invoked from the shared preset's ``postUpgradeTasks`` on the conformance-package
and lock-refresh lanes, after Renovate has already updated ``uv.lock``.

Why this exists (FND-607)
-------------------------
The contract ledger is a *generated* artifact whose content depends on the
version of the conformance package that generated it: the SDK contract-base field
registry the generator reads (``_sdk_contract_mixins``) grows as the SDK gains
fields on ``Input`` / ``Output`` / ``PublishInputMixin``. B006 fires when a live
entrypoint contract field is absent from the ledger.

Those two facts collide with how the checker is installed. CI runs
``uvx atlan-application-sdk-conformance detect`` — unpinned, so always the latest
published release — while the ledger in each app repo was generated by whatever
version that repo's ``uv.lock`` pinned at the time. The instant a conformance
release adds a field to that registry, every app whose lock still points at the
previous release fails B006, on a BLOCK-tier rule, until its ledger is
regenerated. FND-607 is that state: the checker demanded ``Input.app_name`` and
the repo's locked generator (0.17.0, predating the registry entry) could not
produce it.

The conformance lane already exists to close that gap — a dedicated,
auto-merge-on-green PR that moves the lock to the new release. Without this
driver, that PR is red on the very rule the release introduced and needs a human
in each of the fleet's repos. With it, the lock bump and the ledger regeneration
land in the same branch, the lane goes green, and the wave self-heals in one
Renovate cycle.

Why the version is read from the lock rather than passed in
-----------------------------------------------------------
Renovate does not shell-expand ``postUpgradeTasks`` commands, so there is no way
to interpolate the upgraded version into the command string (a ``${VAR}`` is
passed through literally). The command must therefore be argument-free and read
the version itself. Reading it from the just-updated ``uv.lock`` is also the more
honest source: it is what the repo will actually resolve after the PR merges,
whereas ``uvx <pkg>`` with no pin would regenerate against latest and could
record fields from a release this PR does not adopt.

Isolation: the generator runs via ``uvx`` in its own ephemeral environment rather
than through ``uv run`` in the app's. The app's dev environment is irrelevant to
generating the ledger (the generator is a pure AST scan of the repo), some
connector repos need private indexes or system libraries to sync at all, and a
``uv run`` here could rewrite the very lockfile Renovate just produced.

No-op conditions (exit 0, nothing written)
------------------------------------------
* no ``contract_schema.lock.json`` in the repo — the ledger is write-if-absent
  and owned by ``bootstrap``; a repo that has not adopted it must not acquire one
  from a dependency bump;
* no ``atlan-application-sdk-conformance`` entry in ``uv.lock`` — the lane cannot
  have moved a package the repo does not declare (e.g. the lock-refresh lane
  running on a repo that pins conformance nowhere).

Everything else is an error: a failure here must be loud, because the preset sets
``statusCheckWhen.artifactError=always`` and the auto-approve workflow withholds
the code-owner approval unless ``renovate/artifacts`` is green. A silently
skipped regeneration would auto-merge a lock bump that leaves the ledger stale —
exactly the state this driver exists to prevent.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path

PACKAGE = "atlan-application-sdk-conformance"
LEDGER_NAME = "contract_schema.lock.json"
LOCK_NAME = "uv.lock"

# A published version this driver is willing to pass to `uvx <pkg>==<version>`.
# The lock is machine-generated so this is a sanity bound, not a parser: it keeps
# anything that is not a plain PEP 440 release/pre-release string from reaching a
# subprocess argument.
_VERSION_RE = re.compile(r"^[0-9]+(\.[0-9]+)*((a|b|rc)[0-9]+)?(\.post[0-9]+)?$")


def locked_version(lock_text: str, package: str = PACKAGE) -> str | None:
    """Return *package*'s version in a ``uv.lock``, or None if it is not locked."""
    try:
        data = tomllib.loads(lock_text)
    except tomllib.TOMLDecodeError as exc:
        raise SystemExit(f"error: {LOCK_NAME} is not valid TOML: {exc}") from exc

    packages = data.get("package")
    if not isinstance(packages, list):
        return None
    for entry in packages:
        if not isinstance(entry, dict) or entry.get("name") != package:
            continue
        version = entry.get("version")
        if isinstance(version, str) and version:
            return version
    return None


def regen_argv(version: str) -> list[str]:
    """Build the pinned generator invocation for *version*."""
    if not _VERSION_RE.match(version):
        raise SystemExit(
            f"error: refusing to run the generator at unrecognised version "
            f"{version!r} read from {LOCK_NAME}."
        )
    return [
        "uvx",
        f"{PACKAGE}=={version}",
        "gen-contract-ledger",
    ]


def run(repo: Path) -> int:
    """Regenerate *repo*'s ledger at its locked conformance version."""
    ledger = repo / LEDGER_NAME
    if not ledger.is_file():
        print(f"no {LEDGER_NAME} in {repo} — nothing to regenerate.")
        return 0

    lock = repo / LOCK_NAME
    if not lock.is_file():
        print(f"no {LOCK_NAME} in {repo} — nothing to regenerate.")
        return 0

    version = locked_version(lock.read_text(encoding="utf-8"))
    if version is None:
        print(f"{PACKAGE} is not in {LOCK_NAME} — nothing to regenerate.")
        return 0

    argv = regen_argv(version)
    print(f"regenerating {LEDGER_NAME} with {PACKAGE}=={version}")
    result = subprocess.run(argv, cwd=repo)
    if result.returncode != 0:
        print(
            f"error: {' '.join(argv)} failed with exit {result.returncode}.",
            file=sys.stderr,
        )
        return result.returncode
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate contract_schema.lock.json at the conformance version "
            "pinned in uv.lock. Argument-free by design when Renovate invokes "
            "it — postUpgradeTasks commands are not shell-expanded."
        )
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=Path.cwd(),
        help="Repo root to regenerate in (default: cwd, which is the branch "
        "worktree when Renovate runs this).",
    )
    args = parser.parse_args(argv)
    return run(args.repo)


if __name__ == "__main__":
    sys.exit(main())
