apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-sa
  namespace: {{ .Values.temporal.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-role
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-sync-role
subjects:
  - kind: ServiceAccount
    name: secret-sync-sa
    namespace: {{ .Values.temporal.namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-postgres-secret
  namespace: {{ .Values.temporal.namespace }}
spec:
  template:
    spec:
      serviceAccountName: secret-sync-sa
      containers:
      - name: sync-secret
        image: bitnami/kubectl:latest
        env:
        - name: TEMPORAL_CLUSTER_NAMESPACE
          value: {{ .Values.temporal.namespace }}
        command:
          - /bin/sh
          - -c
          - |
            # Detect the namespace of the secret dynamically
            POSTGRES_NAMESPACE=$(kubectl get secrets --all-namespaces | grep postgres-cluster-app | awk '{print $1}')

            if [ -z "$POSTGRES_NAMESPACE" ]; then
              echo "Error: Unable to find the namespace for secret 'postgres-cluster-app'"
              exit 1
            fi

            echo "Detected PostgreSQL secret namespace: $POSTGRES_NAMESPACE"

            # Sync secret to Temporal namespace
            kubectl get secret postgres-cluster-app -n $POSTGRES_NAMESPACE -o yaml \
            | sed "s/name: postgres-cluster-app/name: postgres-creds/" \
            | sed "s/namespace: $POSTGRES_NAMESPACE/namespace: $TEMPORAL_CLUSTER_NAMESPACE/" \
            | sed '/creationTimestamp/d' \
            | sed '/resourceVersion/d' \
            | sed '/ownerReferences:/,+4d' \
            | sed '/uid/d' \
            | kubectl apply -f -
      restartPolicy: OnFailure
