name: Atlan Application Python Pre-commit Checks
on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

jobs:
  pre-commit:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      shell: bash
      run: |
        uv sync --all-extras
        poe download-components

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        uv sync --all-extras
    - uses: pre-commit/action@v3.0.1
