"""Derive a connector's integration-coverage picture from the repo itself.

Nothing here is hand-maintained. Every input is either generated by the app's
own build (``app/generated/``), declared by the app's source (``@entrypoint``),
declared by its tests (``Scenario.entrypoint``), or observed in CI (the GitHub
Actions API). Apps evolve; a stored checklist goes stale the moment someone adds
an entrypoint, so the checklist is rebuilt on every run.

Four things are read:

``@entrypoint`` methods
    The product workflows — the denominator. Falls back to a ``run()`` override
    on an App subclass, which is how single-workflow apps declare theirs.

``app/generated/**/manifest.json``
    The Automation Engine DAG. A node's ``workflow_type`` says whether it runs the
    app's own code (``<connector>:crawler``, or a bare connector name on a
    single-workflow app) or a system app (``PublishWorkflow``,
    ``QueryIntelligenceWorkflow``). That is the integration/e2e boundary,
    generated rather than judged. ``app_name`` is NOT usable: some apps route
    their own nodes through ``automation-engine`` and some ship an unresolved
    ``{app_name}`` placeholder.

``Scenario(entrypoint=..., schema_base_path=..., expected_data=...)``
    Which workflow a suite covers, and how deeply it validates the output. Both
    are declared fields (see T020), so both are a static read.

GitHub Actions
    Whether the job that runs a suite fires on an automatic trigger, and whether
    it is green.
"""

from __future__ import annotations

import ast
import json
from dataclasses import dataclass, field
from pathlib import Path

from conformance.ledger.schema import Boundary, Depth

#: Decorator that declares a product workflow.
_ENTRYPOINT_DECORATOR = "entrypoint"

#: Base classes whose ``run()`` override is itself the product workflow.
_APP_BASE_CLASSES = frozenset(
    {"App", "BaseMetadataExtractor", "SqlApp", "BaseSQLMetadataExtractor"}
)

#: Scenario keywords that declare how deeply a suite validates its output.
#: Ordered strongest first; the first present wins.
_DEPTH_KEYWORDS: tuple[tuple[str, Depth], ...] = (
    ("expected_data", Depth.GOLDEN),
    ("schema_base_path", Depth.VALIDATED),
)

_SKIP_DIRS = frozenset({"__pycache__", ".venv", "node_modules", ".git"})


def _iter_python(base: Path):
    for path in base.rglob("*.py"):
        if not _SKIP_DIRS.isdisjoint(path.parts):
            continue
        try:
            yield path, ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError, OSError):
            continue


def _decorator_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names: set[str] = set()
    for dec in node.decorator_list:
        target = dec.func if isinstance(dec, ast.Call) else dec
        name = (
            target.attr
            if isinstance(target, ast.Attribute)
            else getattr(target, "id", None)
        )
        if name:
            names.add(name)
    return names


def _is_app_subclass(node: ast.ClassDef) -> bool:
    for base in node.bases:
        name = (
            base.attr if isinstance(base, ast.Attribute) else getattr(base, "id", None)
        )
        if name in _APP_BASE_CLASSES:
            return True
    return False


# ---------------------------------------------------------------------------
# 1. The denominator
# ---------------------------------------------------------------------------


def discover_workflows(repo: Path) -> dict[str, str]:
    """Map product-workflow name -> ``path:line`` where it is declared.

    ``run()`` counts only when the app declares no ``@entrypoint``: where both
    exist, ``run()`` is the SDK orchestrator those entrypoints dispatch through,
    not something a user can trigger.
    """
    app_dir = repo / "app"
    if not app_dir.is_dir():
        return {}

    entrypoints: dict[str, str] = {}
    run_overrides: dict[str, str] = {}

    for path, tree in _iter_python(app_dir):
        rel = path.relative_to(repo)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if _ENTRYPOINT_DECORATOR in _decorator_names(node):
                    entrypoints.setdefault(node.name, f"{rel}:{node.lineno}")
            elif isinstance(node, ast.ClassDef) and _is_app_subclass(node):
                for child in node.body:
                    if (
                        isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
                        and child.name == "run"
                    ):
                        run_overrides.setdefault("run", f"{rel}:{child.lineno}")

    return entrypoints or run_overrides


# ---------------------------------------------------------------------------
# 2. The integration/e2e boundary, from the generated AE manifest
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DagNode:
    name: str
    app_name: str
    workflow_type: str | None


def _find_dag(raw: object) -> dict[str, object]:
    """Locate the ``dag`` block, which some manifests nest one level down."""
    if not isinstance(raw, dict):
        return {}
    dag: object = raw.get("dag")
    if not isinstance(dag, dict):
        for value in raw.values():
            if isinstance(value, dict) and isinstance(value.get("dag"), dict):
                dag = value["dag"]
                break
    return dag if isinstance(dag, dict) else {}


def _load_dag(manifest: Path) -> list[DagNode]:
    try:
        raw: object = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    nodes: list[DagNode] = []
    for name, body in _find_dag(raw).items():
        if not isinstance(body, dict):
            continue
        raw_inputs: object = body.get("inputs")
        inputs: dict[str, object] = raw_inputs if isinstance(raw_inputs, dict) else {}
        workflow_type = inputs.get("workflow_type")
        nodes.append(
            DagNode(
                name=str(name),
                app_name=str(body.get("app_name") or inputs.get("app_name") or ""),
                workflow_type=workflow_type if isinstance(workflow_type, str) else None,
            )
        )
    return nodes


def discover_boundary(repo: Path, connector: str) -> dict[str, Boundary]:
    """Map ``<manifest-dir>/<node>`` -> which side of the handoff it sits on.

    The discriminator is ``workflow_type``, not ``app_name``. A node running the
    app's own code is typed ``<connector>:<entrypoint>``; the system apps use a
    bare workflow name (``PublishWorkflow``, ``LineageWorkflow``,
    ``QueryIntelligenceWorkflow``). ``app_name`` cannot be used: some apps route
    their own process/lineage/post-publish nodes through ``automation-engine``,
    and some ship an unresolved ``{app_name}`` placeholder.
    """
    return {
        node: Boundary.TRANSFORMED if workflow else Boundary.POST_PUBLISH
        for node, workflow in _dag_nodes_to_workflow(repo, connector).items()
    }


def _connector_stems(connector: str) -> set[str]:
    """Prefixes a manifest may use for the app's own workflow types."""
    stem = connector.removeprefix("atlan-").removesuffix("-app")
    return {stem, f"{stem}-app", connector}


def _dag_nodes_to_workflow(repo: Path, connector: str) -> dict[str, str | None]:
    """Map ``<manifest-dir>/<node>`` -> the app ``@entrypoint`` it runs.

    ``None`` means a system app. Three ``workflow_type`` forms occur in the
    fleet:

    ``<connector>:crawler``    prefixed — the app's own, suffix names the entrypoint
    ``<connector>:process-metadata``  same, kebab-case mapped to snake_case
    ``<connector>``          bare, matching the connector — a single-workflow app
    ``PublishWorkflow``     bare, not matching — a system app

    Keys are manifest-qualified because a multi-entrypoint app ships one manifest
    per entrypoint and each has its own ``extract`` node; keying on the bare node
    name would let them overwrite one another.
    """
    stems = _connector_stems(connector)
    mapping: dict[str, str | None] = {}

    for manifest in sorted(repo.glob("**/generated/**/manifest.json")):
        if not _SKIP_DIRS.isdisjoint(manifest.parts):
            continue
        scope = manifest.parent.name
        for node in _load_dag(manifest):
            workflow_type = node.workflow_type or ""
            prefix, sep, suffix = workflow_type.partition(":")
            if sep and prefix in stems and suffix:
                workflow = suffix.replace("-", "_")
            elif not sep and workflow_type in stems:
                # Bare connector name: a single-workflow app, whose product
                # workflow is its ``run()`` override.
                workflow = "run"
            else:
                workflow = None
            mapping[f"{scope}/{node.name}"] = workflow
    return mapping


# ---------------------------------------------------------------------------
# 3. What the tests declare
# ---------------------------------------------------------------------------


@dataclass
class DeclaredCoverage:
    """What a repo's test suites declare, per workflow."""

    depth: dict[str, Depth] = field(default_factory=dict)
    sources: dict[str, list[str]] = field(default_factory=dict)

    def record(self, workflow: str, depth: Depth, source: str) -> None:
        best = self.depth.get(workflow)
        if best is None or _DEPTH_ORDER[depth] > _DEPTH_ORDER[best]:
            self.depth[workflow] = depth
        self.sources.setdefault(workflow, []).append(source)


_DEPTH_ORDER = {
    Depth.NONE: 0,
    Depth.ENVELOPE: 1,
    Depth.COUNTS: 2,
    Depth.VALIDATED: 3,
    Depth.GOLDEN: 4,
}


def _const_str(node: ast.AST | None) -> str | None:
    return (
        node.value
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
        else None
    )


def _kw(call: ast.Call, name: str) -> ast.AST | None:
    for keyword in call.keywords:
        if keyword.arg == name:
            return keyword.value
    return None


def _scenario_depth(call: ast.Call) -> Depth:
    for name, depth in _DEPTH_KEYWORDS:
        if _kw(call, name) is not None:
            return depth
    return Depth.COUNTS


def _class_entrypoints(tree: ast.AST) -> dict[int, str]:
    """Line -> class-level ``entrypoint`` covering it."""
    covered: dict[int, str] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        declared: str | None = None
        for stmt in node.body:
            targets = (
                stmt.targets
                if isinstance(stmt, ast.Assign)
                else [stmt.target]
                if isinstance(stmt, ast.AnnAssign)
                else []
            )
            if any(getattr(t, "id", None) == "entrypoint" for t in targets):
                declared = _const_str(stmt.value)
        if declared:
            end = getattr(node, "end_lineno", node.lineno) or node.lineno
            for line in range(node.lineno, end + 1):
                covered[line] = declared
    return covered


def discover_declared_coverage(repo: Path) -> DeclaredCoverage:
    """Read every ``Scenario(api="workflow", ...)`` a repo's tests declare.

    Depth comes from the same declaration: ``expected_data`` means the runner
    byte-compares against a committed expectation, ``schema_base_path`` means it
    validates the transformed output against a schema. Neither is inferred from
    assertion source — both are fields the SDK runner acts on.
    """
    tests_dir = repo / "tests"
    coverage = DeclaredCoverage()
    if not tests_dir.is_dir():
        return coverage

    for path, tree in _iter_python(tests_dir):
        rel = str(path.relative_to(repo))
        by_class = _class_entrypoints(tree)
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            name = (
                func.attr
                if isinstance(func, ast.Attribute)
                else getattr(func, "id", None)
            )
            if name != "Scenario":
                continue
            if _const_str(_kw(node, "api")) != "workflow":
                continue
            if _kw(node, "skip") is not None and getattr(
                _kw(node, "skip"), "value", False
            ):
                continue

            workflow = _const_str(_kw(node, "entrypoint")) or by_class.get(node.lineno)
            if not workflow:
                continue
            coverage.record(workflow, _scenario_depth(node), f"{rel}:{node.lineno}")

    return coverage
