"""Tests for the two schema sources (ADR-0020, FND-686).

The fixture is a **byte copy of real contract-toolkit output** —
``contract-toolkit/examples/artifact-schemas/app/generated/artifact_schemas.json``,
generated by the toolkit's own example. A hand-built declaration object would test
the dataclasses and skip the loader; a hand-written JSON blob would test the loader
against a shape nobody generates. :func:`test_fixture_is_the_generated_example`
holds the copy honest, so a change to what the toolkit emits fails here rather than
in production.

Three properties are worth defending, because each has a quiet failure mode:

* **The loader reads what the toolkit writes** — every field, its logical type, its
  ``required`` flag and its ``description``, including the nested dotted and ``[]``
  paths, which is the shape a recursive-grammar rewrite would silently drop.
* **Two answers, not one.** "No declaration" (``None``) and "unreadable
  declaration" (``ArtifactDeclarationError``) stay apart. Collapsed, a loader
  failure would be reported as ``not_declared`` — a finding against an app for a
  file it wrote correctly.
* **Nothing dict-shaped on the seam.** A source hands back typed declarations, and
  the entrypoint-level query hands back a tuple of names.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

import orjson
import pytest

from application_sdk.validation.artifacts import (
    FORMAT_NDJSON,
    FORMAT_PARQUET,
    DeclaredField,
    FieldMapDeclaration,
    ModelDeclaration,
)
from application_sdk.validation.protocols import SchemaSource
from application_sdk.validation.sources import (
    ARTIFACT_SCHEMAS_ENVELOPE_VERSION,
    ARTIFACT_SCHEMAS_FILENAME,
    ArtifactDeclarationError,
    ContractSource,
    ModelSource,
    _load_schemas,
    artifact_schema_paths,
    declared_artifact_fields,
)

RESOURCES = Path(__file__).parent / "resources"
FIXTURE = RESOURCES / ARTIFACT_SCHEMAS_FILENAME

TOOLKIT_EXAMPLE = (
    Path(__file__).parents[3]
    / "contract-toolkit"
    / "examples"
    / "artifact-schemas"
    / "app"
    / "generated"
    / ARTIFACT_SCHEMAS_FILENAME
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def generated_dir(tmp_path: Path) -> Path:
    """A generated-contract directory holding the real toolkit output, flat.

    ``_load_schemas`` is cached per path and ``tmp_path`` is unique per test, so no
    cache clearing is needed — but the cache is cleared anyway so a test that writes
    to a fixed path cannot inherit another test's parse.
    """
    _load_schemas.cache_clear()
    (tmp_path / ARTIFACT_SCHEMAS_FILENAME).write_bytes(FIXTURE.read_bytes())
    return tmp_path


def _write(path: Path, document: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(orjson.dumps(document))


def _valid_document(**overrides: object) -> dict:
    """The smallest document the loader accepts, before ``overrides`` are applied."""
    document = {
        "version": ARTIFACT_SCHEMAS_ENVELOPE_VERSION,
        "schemas": {
            "edges": {
                "format": FORMAT_NDJSON,
                "fields": [
                    {
                        "name": "process_id",
                        "type": "string",
                        "required": True,
                        "description": "Groups edges into one lineage process.",
                    }
                ],
            }
        },
    }
    document.update(overrides)
    return document


def _field(declaration: FieldMapDeclaration, path: str) -> DeclaredField:
    match = [f for f in declaration.fields if f.path == path]
    assert match, f"{path} not declared; got {[f.path for f in declaration.fields]}"
    return match[0]


# ---------------------------------------------------------------------------
# The fixture is real generated output
# ---------------------------------------------------------------------------


def test_fixture_is_the_generated_example() -> None:
    """The committed fixture is byte-identical to the toolkit's own example.

    Copied rather than read in place so the validation suite stays self-contained,
    and guarded rather than trusted so the copy cannot drift: the loader's contract
    *is* the toolkit's output shape, and a change to one that does not reach the
    other is precisely the producer/consumer disagreement this capability exists to
    catch — here, between the toolkit and the SDK themselves.
    """
    assert TOOLKIT_EXAMPLE.exists(), f"toolkit example missing at {TOOLKIT_EXAMPLE}"
    assert FIXTURE.read_bytes() == TOOLKIT_EXAMPLE.read_bytes(), (
        f"{FIXTURE} has drifted from {TOOLKIT_EXAMPLE}. Re-copy it: the SDK loader "
        f"must keep reading exactly what the contract toolkit generates."
    )


# ---------------------------------------------------------------------------
# ContractSource — the happy path, against real generated output
# ---------------------------------------------------------------------------


def test_source_satisfies_the_protocol() -> None:
    assert isinstance(ContractSource(field="raw_queries"), SchemaSource)
    assert isinstance(ModelSource(model=DeclaredField), SchemaSource)


def test_kinds_are_the_pinned_telemetry_values() -> None:
    """These land on the outcome event; rewording them breaks queries in place."""
    assert ContractSource(field="x").kind == "contract"
    assert ModelSource(model=DeclaredField).kind == "model"


def test_loads_a_parquet_declaration(generated_dir: Path) -> None:
    declaration = ContractSource(
        field="raw_queries", generated_dir=generated_dir
    ).resolve()

    assert isinstance(declaration, FieldMapDeclaration)
    assert declaration.artifact_format == FORMAT_PARQUET
    assert declaration.field_count == 6
    assert [f.path for f in declaration.fields] == [
        "QUERY_ID",
        "START_TIME",
        "CREDITS_USED",
        "ROWS_PRODUCED",
        "YEAR",
        "SESSION_PARAMS",
    ]


def test_the_load_bearing_type_survives_the_round_trip(generated_dir: Path) -> None:
    """``START_TIME`` is a ``timestamp``, not a string.

    The single asymmetry the whole capability exists to assert — a 73-day frozen
    lineage marker traced to that one column having become a string. If the loader
    ever flattened the vocabulary, this is the assertion that would notice.
    """
    declaration = ContractSource(
        field="raw_queries", generated_dir=generated_dir
    ).resolve()
    assert declaration is not None
    assert _field(declaration, "START_TIME").type == "timestamp"
    assert _field(declaration, "QUERY_ID").type == "string"


def test_optional_and_extended_types_survive(generated_dir: Path) -> None:
    declaration = ContractSource(
        field="raw_queries", generated_dir=generated_dir
    ).resolve()
    assert declaration is not None

    credits = _field(declaration, "CREDITS_USED")
    assert credits.required is False
    assert credits.type == "float"

    # `decimal` is an extension member: a Snowflake NUMBER lands as parquet
    # decimal128, and asserting float would mis-flag it or lose precision.
    assert _field(declaration, "ROWS_PRODUCED").type == "decimal"
    # `json` is physically a string column and semantically not — collapsing the
    # two would defeat this hop's check.
    assert _field(declaration, "SESSION_PARAMS").type == "json"


def test_nested_paths_load_verbatim(generated_dir: Path) -> None:
    """Dotted paths and ``[]`` element steps are carried through unchanged.

    Nested payloads are declared as a *flat set of paths plus container types*, not
    a recursive grammar. A loader that parsed the paths into a tree would have to
    re-serialise them for the validator, and ``[]`` — which says "descend into the
    list" in logical terms rather than parquet's encoding-dependent
    ``columns.list.element`` — is exactly what such a round trip loses.
    """
    declaration = ContractSource(
        field="transformed_entities", generated_dir=generated_dir
    ).resolve()
    assert declaration is not None
    assert declaration.artifact_format == FORMAT_NDJSON

    paths = [f.path for f in declaration.fields]
    assert "attributes" in paths
    assert "attributes.qualifiedName" in paths
    assert "attributes.columns" in paths
    assert "attributes.columns[]" in paths
    assert "attributes.columns[].name" in paths

    assert _field(declaration, "attributes").type == "struct"
    assert _field(declaration, "attributes.columns").type == "array"
    assert _field(declaration, "attributes.columns[]").type == "struct"
    assert _field(declaration, "attributes.columns[].order").type == "int"
    assert _field(declaration, "attributes.tags[]").type == "string"
    # `any` is "must be present, type not asserted" — declared rather than someone
    # inventing a wrong type to satisfy the vocabulary.
    assert _field(declaration, "customAttributes").type == "any"


def test_descriptions_are_carried_through(generated_dir: Path) -> None:
    """The toolkit requires a description per field; the loader must not drop it.

    It is the only place a ``type = "any"`` field can say what it is, and it is read
    by whoever is debugging the hand-off that just failed.
    """
    declaration = ContractSource(
        field="raw_queries", generated_dir=generated_dir
    ).resolve()
    assert declaration is not None
    assert all(f.description for f in declaration.fields)
    assert "join key" in _field(declaration, "QUERY_ID").description


def test_an_input_artifact_is_declarable(generated_dir: Path) -> None:
    """The consumer declares what it requires of what it *reads*, not just writes."""
    declaration = ContractSource(
        field="upstream_lineage", generated_dir=generated_dir
    ).resolve()
    assert isinstance(declaration, FieldMapDeclaration)
    assert declaration.field_count == 3


def test_declarations_are_frozen(generated_dir: Path) -> None:
    """Nothing hands out a mutable declaration — the parse is cached and shared."""
    declaration = ContractSource(
        field="raw_queries", generated_dir=generated_dir
    ).resolve()
    assert declaration is not None
    with pytest.raises(dataclasses.FrozenInstanceError):
        # Deliberate: assigning to a frozen field is the thing under test, so the
        # checker's complaint is the behaviour being asserted at runtime.
        declaration.fields[0].type = "string"  # type: ignore[misc]


# ---------------------------------------------------------------------------
# ContractSource — "no declaration" is None, and only None
# ---------------------------------------------------------------------------


def test_no_generated_file_is_not_an_error(tmp_path: Path) -> None:
    """The unadopted state: the toolkit emits no file when an app declares nothing."""
    _load_schemas.cache_clear()
    assert ContractSource(field="anything", generated_dir=tmp_path).resolve() is None


def test_undeclared_field_is_none(generated_dir: Path) -> None:
    assert (
        ContractSource(field="not_declared_here", generated_dir=generated_dir).resolve()
        is None
    )


# ---------------------------------------------------------------------------
# ContractSource — malformed input raises, never returns None
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("case", "document"),
    [
        ("newer envelope", _valid_document(version=2)),
        ("no envelope", _valid_document(version=None)),
        ("top level is a list", []),
        ("schemas is not an object", _valid_document(schemas=[])),
        (
            "schema entry is not an object",
            _valid_document(schemas={"edges": "ndjson"}),
        ),
        (
            "no format declared",
            _valid_document(schemas={"edges": {"fields": [{"name": "a"}]}}),
        ),
        (
            "no fields list",
            _valid_document(schemas={"edges": {"format": FORMAT_NDJSON}}),
        ),
        (
            "zero fields",
            _valid_document(schemas={"edges": {"format": FORMAT_NDJSON, "fields": []}}),
        ),
        (
            "field is not an object",
            _valid_document(
                schemas={"edges": {"format": FORMAT_NDJSON, "fields": ["a"]}}
            ),
        ),
        (
            "field has no name",
            _valid_document(
                schemas={
                    "edges": {"format": FORMAT_NDJSON, "fields": [{"type": "string"}]}
                }
            ),
        ),
        (
            "required is not a boolean",
            _valid_document(
                schemas={
                    "edges": {
                        "format": FORMAT_NDJSON,
                        "fields": [{"name": "a", "required": "yes"}],
                    }
                }
            ),
        ),
    ],
)
def test_malformed_declaration_raises_rather_than_returning_none(
    tmp_path: Path, case: str, document: object
) -> None:
    """Every malformed shape is an error, and specifically *not* ``None``.

    ``None`` means ``not_declared``, which on a public boundary is a finding against
    the app. A file the app wrote and the SDK could not read must never be reported
    that way — the wrapper turns this raise into ``absent`` plus a warning instead.
    """
    _load_schemas.cache_clear()
    _write(tmp_path / ARTIFACT_SCHEMAS_FILENAME, document)
    with pytest.raises(ArtifactDeclarationError):
        ContractSource(field="edges", generated_dir=tmp_path).resolve()


def test_zero_field_schema_is_refused_by_name(tmp_path: Path) -> None:
    """A hand-edited zero-field schema cannot reintroduce "adopted but checks nothing"."""
    _load_schemas.cache_clear()
    _write(
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(schemas={"edges": {"format": FORMAT_NDJSON, "fields": []}}),
    )
    with pytest.raises(ArtifactDeclarationError, match="zero fields"):
        ContractSource(field="edges", generated_dir=tmp_path).resolve()


def test_unparseable_json_raises(tmp_path: Path) -> None:
    _load_schemas.cache_clear()
    (tmp_path / ARTIFACT_SCHEMAS_FILENAME).write_text("{not json")
    with pytest.raises(ArtifactDeclarationError, match="not valid JSON"):
        ContractSource(field="edges", generated_dir=tmp_path).resolve()


def test_empty_file_raises(tmp_path: Path) -> None:
    """Empty is malformed, not absent: the toolkit never writes a zero-byte file."""
    _load_schemas.cache_clear()
    (tmp_path / ARTIFACT_SCHEMAS_FILENAME).write_bytes(b"")
    with pytest.raises(ArtifactDeclarationError):
        ContractSource(field="edges", generated_dir=tmp_path).resolve()


def test_unknown_logical_type_is_not_policed(tmp_path: Path) -> None:
    """A newer toolkit's type loads; the *validator* resolves it to unsupported.

    Rejecting the whole file would drop every other assertion in it because one
    field used a member this SDK has not learned yet.
    """
    _load_schemas.cache_clear()
    _write(
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(
            schemas={
                "edges": {
                    "format": FORMAT_NDJSON,
                    "fields": [{"name": "a", "type": "geography"}],
                }
            }
        ),
    )
    declaration = ContractSource(field="edges", generated_dir=tmp_path).resolve()
    assert declaration is not None
    assert _field(declaration, "a").type == "geography"


def test_unknown_format_is_not_policed(tmp_path: Path) -> None:
    """Same reasoning one level up: dispatch reports ``unsupported``, not ``absent``."""
    _load_schemas.cache_clear()
    _write(
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(
            schemas={"edges": {"format": "avro", "fields": [{"name": "a"}]}}
        ),
    )
    declaration = ContractSource(field="edges", generated_dir=tmp_path).resolve()
    assert declaration is not None
    assert declaration.artifact_format == "avro"


# ---------------------------------------------------------------------------
# Path resolution across the single- and multi-entrypoint layouts
# ---------------------------------------------------------------------------


def test_single_entrypoint_looks_only_at_the_flat_file(tmp_path: Path) -> None:
    assert artifact_schema_paths(generated_dir=tmp_path) == (
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
    )


def test_multi_entrypoint_prefers_its_own_file(tmp_path: Path) -> None:
    assert artifact_schema_paths(entrypoint="extract", generated_dir=tmp_path) == (
        tmp_path / "extract" / ARTIFACT_SCHEMAS_FILENAME,
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
    )


def test_entrypoint_file_wins_over_the_flat_one(tmp_path: Path) -> None:
    _load_schemas.cache_clear()
    _write(
        tmp_path / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(
            schemas={
                "edges": {
                    "format": FORMAT_NDJSON,
                    "fields": [{"name": "flat", "type": "string"}],
                }
            }
        ),
    )
    _write(
        tmp_path / "extract" / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(
            schemas={
                "edges": {
                    "format": FORMAT_NDJSON,
                    "fields": [{"name": "per_entrypoint", "type": "string"}],
                }
            }
        ),
    )
    declaration = ContractSource(
        field="edges", entrypoint="extract", generated_dir=tmp_path
    ).resolve()
    assert declaration is not None
    assert [f.path for f in declaration.fields] == ["per_entrypoint"]


def test_an_entrypoints_own_file_is_the_final_answer(tmp_path: Path) -> None:
    """A field its own file omits is ``not_declared`` — never the flat file's answer.

    Falling through would answer one entrypoint's question with another scope's
    declarations. The toolkit removes the bundle-root half of that hazard by
    refusing to generate a root file; this is the loader's half.
    """
    _load_schemas.cache_clear()
    _write(tmp_path / ARTIFACT_SCHEMAS_FILENAME, _valid_document())
    _write(
        tmp_path / "extract" / ARTIFACT_SCHEMAS_FILENAME,
        _valid_document(
            schemas={
                "other": {
                    "format": FORMAT_NDJSON,
                    "fields": [{"name": "a", "type": "string"}],
                }
            }
        ),
    )
    assert (
        ContractSource(
            field="edges", entrypoint="extract", generated_dir=tmp_path
        ).resolve()
        is None
    )


def test_flat_file_is_used_when_the_entrypoint_has_no_file(tmp_path: Path) -> None:
    """A single-entrypoint app still knows its entrypoint name; the fallback is safe."""
    _load_schemas.cache_clear()
    _write(tmp_path / ARTIFACT_SCHEMAS_FILENAME, _valid_document())
    declaration = ContractSource(
        field="edges", entrypoint="extract", generated_dir=tmp_path
    ).resolve()
    assert isinstance(declaration, FieldMapDeclaration)


# ---------------------------------------------------------------------------
# declared_artifact_fields — the entrypoint-level question
# ---------------------------------------------------------------------------


def test_declared_fields_lists_names_only(generated_dir: Path) -> None:
    """A tuple of names, not a mapping: no dict-shaped API on the source seam."""
    names = declared_artifact_fields(generated_dir=generated_dir)
    assert names == ("raw_queries", "transformed_entities", "upstream_lineage")
    assert isinstance(names, tuple)


def test_declared_fields_is_empty_when_nothing_is_declared(tmp_path: Path) -> None:
    _load_schemas.cache_clear()
    assert declared_artifact_fields(generated_dir=tmp_path) == ()


def test_declared_fields_propagates_a_malformed_file(tmp_path: Path) -> None:
    """A registration-time caller gets the error, not a silently empty set.

    An empty tuple means "this entrypoint declares nothing", which is what a
    boundary check turns into a warning against the app. A file that failed to parse
    must not be able to produce that answer.
    """
    _load_schemas.cache_clear()
    (tmp_path / ARTIFACT_SCHEMAS_FILENAME).write_text("{not json")
    with pytest.raises(ArtifactDeclarationError):
        declared_artifact_fields(generated_dir=tmp_path)


# ---------------------------------------------------------------------------
# ModelSource
# ---------------------------------------------------------------------------


class _Model:
    """Stands in for a pyatlan_v9 asset: all that is asked is a callable ``validate``."""

    def validate(self) -> list[str]:
        return []


def test_model_source_resolves_to_delegation() -> None:
    declaration = ModelSource(model=_Model).resolve()
    assert isinstance(declaration, ModelDeclaration)
    assert declaration.model is _Model
    assert declaration.artifact_format == FORMAT_NDJSON
    # A model declares no enumerable field list at this layer — the count is 0, and
    # a validator that diffed against it would be diffing against nothing.
    assert declaration.field_count == 0


def test_model_source_never_returns_none() -> None:
    """The model *is* the declaration, so a ModelSource always has one."""
    assert ModelSource(model=_Model).resolve() is not None


def test_model_source_carries_the_parquet_cell() -> None:
    """parquet x model resolves and is refused at dispatch, not here.

    The cell has to be *reachable* for the wrapper to report ``unsupported`` on it.
    Refusing it at construction would turn a stated gap back into silence.
    """
    declaration = ModelSource(model=_Model, artifact_format=FORMAT_PARQUET).resolve()
    assert declaration.artifact_format == FORMAT_PARQUET


def test_model_without_validate_is_an_error() -> None:
    class _NoValidate:
        pass

    with pytest.raises(ArtifactDeclarationError, match="no 'validate' method"):
        ModelSource(model=_NoValidate).resolve()


def test_non_callable_validate_is_an_error() -> None:
    class _NotCallable:
        validate = "nope"

    with pytest.raises(ArtifactDeclarationError, match="not callable"):
        ModelSource(model=_NotCallable).resolve()


def test_an_instance_is_not_a_model() -> None:
    """An easy mistake — passing the asset rather than its class."""
    with pytest.raises(ArtifactDeclarationError, match="must be a class"):
        # Deliberate: passing an instance where a class is required is the mistake
        # under test — the checker catching it is the point, not an obstacle.
        ModelSource(model=_Model()).resolve()  # type: ignore[arg-type]
