"""Typed contracts for built-in App implementations."""

from application_sdk.templates.contracts.base_metadata_extraction import (
    UploadInput,
    UploadOutput,
)
from application_sdk.templates.contracts.incremental_sql import (
    ExecuteColumnBatchInput,
    ExecuteColumnBatchOutput,
    FetchColumnsIncrementalInput,
    FetchIncrementalMarkerInput,
    FetchIncrementalMarkerOutput,
    FetchTablesIncrementalInput,
    IncrementalExtractionInput,
    IncrementalExtractionOutput,
    IncrementalRunContext,
    IncrementalTaskInput,
    PrepareColumnQueriesInput,
    PrepareColumnQueriesOutput,
    ReadCurrentStateInput,
    ReadCurrentStateOutput,
    UpdateMarkerInput,
    UpdateMarkerOutput,
    WriteCurrentStateInput,
    WriteCurrentStateOutput,
)
from application_sdk.templates.contracts.sql_metadata import (
    ExtractionInput,
    ExtractionOutput,
    ExtractionTaskInput,
    FetchColumnsInput,
    FetchColumnsOutput,
    FetchDatabasesInput,
    FetchDatabasesOutput,
    FetchProceduresInput,
    FetchProceduresOutput,
    FetchSchemasInput,
    FetchSchemasOutput,
    FetchTablesInput,
    FetchTablesOutput,
    TransformInput,
    TransformOutput,
)
from application_sdk.templates.contracts.sql_query import (
    QueryBatchInput,
    QueryBatchOutput,
    QueryExtractionInput,
    QueryExtractionOutput,
    QueryFetchInput,
    QueryFetchOutput,
)

__all__ = [
    # Base metadata extraction
    "UploadInput",
    "UploadOutput",
    # SQL metadata — base
    "ExtractionInput",
    "ExtractionOutput",
    "ExtractionTaskInput",
    "FetchColumnsInput",
    "FetchColumnsOutput",
    "FetchDatabasesInput",
    "FetchDatabasesOutput",
    "FetchProceduresInput",
    "FetchProceduresOutput",
    "FetchSchemasInput",
    "FetchSchemasOutput",
    "FetchTablesInput",
    "FetchTablesOutput",
    "TransformInput",
    "TransformOutput",
    # Incremental SQL
    "ExecuteColumnBatchInput",
    "ExecuteColumnBatchOutput",
    "FetchColumnsIncrementalInput",
    "FetchIncrementalMarkerInput",
    "FetchIncrementalMarkerOutput",
    "FetchTablesIncrementalInput",
    "IncrementalExtractionInput",
    "IncrementalExtractionOutput",
    "IncrementalRunContext",
    "IncrementalTaskInput",
    "PrepareColumnQueriesInput",
    "PrepareColumnQueriesOutput",
    "ReadCurrentStateInput",
    "ReadCurrentStateOutput",
    "UpdateMarkerInput",
    "UpdateMarkerOutput",
    "WriteCurrentStateInput",
    "WriteCurrentStateOutput",
    # SQL query
    "QueryBatchInput",
    "QueryBatchOutput",
    "QueryExtractionInput",
    "QueryExtractionOutput",
    "QueryFetchInput",
    "QueryFetchOutput",
]
