---
environments:
  default:
    values:
      - installAtlanDeps:
          enabled: true
      - enableDaprShared:
          enabled: true
      - singleNamespace:
          enabled: false
      - releaseNamespaces:
          atlan: atlan-temporal
          daprShared: atlan-dapr-shared
          app: hello-world-app

  app:
    values:
      - installAtlanDeps:
          enabled: false
      - enableDaprShared:
          enabled: false
      - singleNamespace:
          enabled: false
      - releaseNamespaces:
          app: hello-world-app
      # If singleNamespace is true
      # - releaseNamespaces:
      #     namespace: atlan-secure-agent

  unified:
    values:
      - installAtlanDeps:
          enabled: true
      - enableDaprShared:
          enabled: true
      - singleNamespace: 
          enabled: true
      - releaseNamespaces: 
          namespace: atlan-secure-agent
---
releases:
  - name: atlan
    chart: "./charts/atlan"
    namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.atlan }}{{ end }}'
    createNamespace: true
    version: 0.1.0
    disableValidation: true
    missingFileHandler: Error
    installed: {{ .Environment.Values.installAtlanDeps.enabled }}
    wait: true
    values:
      - singleNamespace:
          enabled: {{ .Environment.Values.singleNamespace.enabled }}
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            if {{ .Environment.Values.installAtlanDeps.enabled }}; then
              if {{ .Environment.Values.enableDaprShared.enabled }}; then
                if {{ .Environment.Values.singleNamespace.enabled }}; then
                  helmfile apply -f ./charts/atlan/helmfile.yaml -e unified --state-values-set releaseNamespaces.namespace={{ .Environment.Values.releaseNamespaces.namespace }},enableDaprInjected.enabled=false
                else
                  helmfile apply -f ./charts/atlan/helmfile.yaml --state-values-set enableDaprInjected.enabled=false
                fi
              else
                if {{ .Environment.Values.singleNamespace.enabled }}; then
                  helmfile apply -f ./charts/atlan/helmfile.yaml -e unified --state-values-set releaseNamespaces.namespace={{ .Environment.Values.releaseNamespaces.namespace }},enableDaprInjected.enabled=true
                else
                  helmfile apply -f ./charts/atlan/helmfile.yaml --state-values-set enableDaprInjected.enabled=true
                fi
              fi
            fi

  - name: dapr-shared-chart
    namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.daprShared }}{{ end }}'
    createNamespace: true
    chart: "./charts/dapr-shared-chart"
    version: 0.0.15
    disableValidation: true
    installed: {{ .Environment.Values.enableDaprShared.enabled }}
    missingFileHandler: Error

  - name: app
    chart: "./charts/app"
    namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.app }}{{ end }}'
    createNamespace: true
    version: 0.1.0
    disableValidation: true
    missingFileHandler: Error
    installed: true
    values:
      - singleNamespace:
          enabled: {{ .Environment.Values.singleNamespace.enabled }}
    needs:
      - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/atlan{{ else }}{{ .Environment.Values.releaseNamespaces.atlan }}/atlan{{ end }}'
      - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/dapr-shared-chart{{ else }}{{ .Environment.Values.releaseNamespaces.daprShared }}/dapr-shared-chart{{ end }}'
