apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-sa
  namespace: {{ .Values.app.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-role
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-sync-role
subjects:
  - kind: ServiceAccount
    name: secret-sync-sa
    namespace: {{ .Values.app.namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-secret-dpar-statestore
  namespace: {{ .Values.app.namespace }}
spec:
  template:
    spec:
      serviceAccountName: secret-sync-sa
      containers:
      - name: sync-secret
        image: bitnami/kubectl:latest
        env:
        - name: APP_NAMESPACE
          value: {{ .Values.app.namespace }}
        command:
          - /bin/sh
          - -c
          - |
            # Detect the namespace of the secret dynamically
            POSTGRES_NAMESPACE=$(kubectl get secrets --all-namespaces | grep postgres-cluster-app | awk '{print $1}')

            if [ -z "$POSTGRES_NAMESPACE" ]; then
              echo "Error: Unable to find the namespace for secret 'postgres-cluster-app'"
              exit 1
            fi

            # Get the app_admin user password
            APP_ADMIN_PASSWORD=$(kubectl get secret postgres-cluster-app -n $POSTGRES_NAMESPACE -o jsonpath="{.data.password}" | base64 --decode)

            # Generate the Dapr connection string
            POSTGRES_HOST="postgres-cluster-rw.${POSTGRES_NAMESPACE}.svc.cluster.local"
            POSTGRES_PORT="5432"
            DATABASE_NAME="dapr"
            CONNECTION_STRING="postgresql://app_admin:$APP_ADMIN_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DATABASE_NAME"

            echo "Creating a secret for the Dapr connection string in the ${APP_NAMESPACE} namespace..."
            kubectl create secret generic dapr-pg-connection-string \
              --from-literal=connection-string="$CONNECTION_STRING" \
              -n $APP_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: OnFailure
