apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: atlan-objectstore
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: atlan-bucket
    - name: region
      value: us-east-1
    - name: endpoint
      value: https://{{tenant}}.atlan.com/api/blobstorage
    - name: accessKey
      secretKeyRef:
        name: client_id
        key:  client_id
    - name: secretKey
      secretKeyRef:
        name: client_secret
        key:  client_secret
    - name: forcePathStyle
      value: "true"
auth:
  secretStore: deployment-secret-store