apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventstore
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: consumerGroup
      value: "dapr-app"
    - name: clientID
      value: "dapr-app"
    - name: authType
      value: "none"
    - name: disableTls
      value: "true"