apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: objectstore
spec:
  version: v1
  type: bindings.localstorage
  ignoreErrors: true
  metadata:
    # Must match DEFAULT_OBJECTSTORE_ROOT in application_sdk/dev/_dapr.py
    - name: rootPath
      value: "./local/dapr/objectstore"