apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  version: v1
  type: secretstores.local.file
  ignoreErrors: true
  metadata:
  - name: secretsFile
    value: ./local/dapr/secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "true"