repositories:
- name: dapr
  url: https://dapr.github.io/helm-charts/
- name: cloudnative-pg
  url: https://cloudnative-pg.github.io/charts
- name: temporal-operator
  url: https://alexandrevilain.github.io/temporal-operator
- name: cert-manager
  url: https://charts.jetstack.io
- name: minio
  url: https://operator.min.io

releases:
- name: dapr
  namespace: dapr
  createNamespace: true
  chart: dapr/dapr
  version: 1.14.4
  disableValidation: true  # Required since it installs CRDs in the same chart https://github.com/roboll/helmfile/pull/1373
  missingFileHandler: Error
  values:
    - values/dapr.yaml

- name: dapr-dashboard
  namespace: dapr
  createNamespace: true
  chart: dapr/dapr-dashboard
  version: 0.15.0
  disableValidation: true  # Required since it installs CRDs in the same chart https://github.com/roboll/helmfile/pull/1373
  missingFileHandler: Error
  values:
    - values/dapr-dashboard.yaml

- name: cloudnative-pg
  namespace: cloudnative-pg
  createNamespace: true
  chart: cloudnative-pg/cloudnative-pg
  version: 0.22.1
  disableValidation: true  # Required since it installs CRDs in the same chart https://github.com/roboll/helmfile/pull/1373
  values:
    - values/cloudnative-pg.yaml

- name: postgres-cluster
  namespace: postgres
  createNamespace: true
  chart: cloudnative-pg/cluster
  version: 0.1.0
  disableValidation: true  # Required since it installs CRDs in the same chart https://github.com/roboll/helmfile/pull/1373
  values:
    - values/cloudnative-pg-cluster.yaml
  needs:
    - cloudnative-pg/cloudnative-pg # Ensure cloudnative-pg is deployed before postgres-cluster

- name: cert-manager
  namespace: cert-manager
  createNamespace: true
  chart: cert-manager/cert-manager
  version: 1.16.1
  disableValidation: true
  values:
    - values/cert-manager.yaml

- name: temporal
  namespace: temporal
  createNamespace: true
  chart: temporal-operator/temporal-operator
  version: 0.5.0
  disableValidation: true
  values:
    - values/temporal-operator.yaml
  needs:
    - cert-manager/cert-manager # Ensure cert-manager is deployed before temporal

- name: minio-operator
  namespace: minio-operator
  createNamespace: true
  chart: minio/operator
  version: 6.0.4
  disableValidation: true
  values:
    - values/minio-operator.yaml

- name: tenant
  namespace: tenant
  createNamespace: true
  chart: minio/tenant
  version: 6.0.4
  disableValidation: true
  values:
    - values/minio-tenant.yaml
  needs:
    - minio-operator/minio-operator # Ensure minio-operator is deployed before tenant
