name: Setup Python Dependencies for Atlan Apps
description: |
  Sets up Python project dependencies and manages dependency caching for Atlan Apps.
  This action handles the installation of Python 3.11, uv package manager, and project dependencies.
  It implements efficient caching strategies to speed up workflow execution by storing and reusing
  the virtual environment.

inputs:
  cache:
    description: "Enable dependency caching"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - uses: astral-sh/setup-uv@v5
      run: |
        uv sync --all-extras
        poe download-components

    - name: Load cached venv
      id: cached-uv-dependencies
      if: ${{ inputs.cache }} == 'true'
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}

    - name: Install dependencies
      shell: bash
      if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      run: uv sync --all-extras
