"""Re-export of :mod:`application_sdk_api.credentials.errors`.

This code lives in the ``atlan-application-sdk-api`` package so the consolidated
API host and the worker share one implementation. ``application_sdk.credentials.errors`` is the
SDK's first-class path to the same objects and is not deprecated.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

from typing import Any as _Any

import application_sdk_api.credentials.errors as _src
from application_sdk_api.credentials.errors import (  # noqa: F401 — re-exported, same objects
    CREDENTIAL_ERROR,
    CREDENTIAL_NOT_FOUND,
    CREDENTIAL_PARSE_ERROR,
    CREDENTIAL_VALIDATION_ERROR,
    AtlanCredentialTypeError,
    Audience,
    AuthError,
    CredentialError,
    CredentialNotFoundError,
    CredentialParseError,
    CredentialResolvableTypeError,
    CredentialRoutingError,
    CredentialValidationError,
    ErrorCode,
    InvalidInputError,
    NotFoundError,
    sanitize_cause_repr,
)

__all__ = [
    "AtlanCredentialTypeError",
    "Audience",
    "AuthError",
    "CREDENTIAL_ERROR",
    "CREDENTIAL_NOT_FOUND",
    "CREDENTIAL_PARSE_ERROR",
    "CREDENTIAL_VALIDATION_ERROR",
    "CredentialError",
    "CredentialNotFoundError",
    "CredentialParseError",
    "CredentialResolvableTypeError",
    "CredentialRoutingError",
    "CredentialValidationError",
    "ErrorCode",
    "InvalidInputError",
    "NotFoundError",
    "sanitize_cause_repr",
]


def __getattr__(name: str) -> _Any:
    # Private names are not re-exported above; resolve them from the source.
    return getattr(_src, name)
