"""Re-export of :mod:`application_sdk_api.credentials.ingress`.

This code lives in the ``atlan-application-sdk-api`` package so the consolidated
API host and the worker share one implementation. ``application_sdk.credentials.ingress`` is the
SDK's first-class path to the same objects and is not deprecated.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

from typing import Any as _Any

import application_sdk_api.credentials.ingress as _src
from application_sdk_api.credentials.ingress import (  # noqa: F401 — re-exported, same objects
    AGENT_JSON_ALIASES,
    AgentCredentialSpec,
    CredentialError,
    SpecT,
    declared_agent_spec_type,
    get_logger,
    lift_agent_json,
    logger,
    normalize_agent_json,
)

__all__ = [
    "AGENT_JSON_ALIASES",
    "AgentCredentialSpec",
    "CredentialError",
    "SpecT",
    "declared_agent_spec_type",
    "get_logger",
    "lift_agent_json",
    "logger",
    "normalize_agent_json",
]


def __getattr__(name: str) -> _Any:
    # Private names are not re-exported above; resolve them from the source.
    return getattr(_src, name)
