{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "dapr-shared-secret-reader") }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dapr-shared.fullname" . }}-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dapr-shared.fullname" . }}-secret-reader
subjects:
- kind: ServiceAccount
  name: {{ include "dapr-shared.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dapr-shared.fullname" . }}-secret-reader
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "dapr-shared-configmap-creator") }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dapr-shared.fullname" . }}-configmap-creator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "delete"]
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dapr-shared.fullname" . }}-configmap-creator
subjects:
- kind: ServiceAccount
  name: {{ include "dapr-shared.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dapr-shared.fullname" . }}-configmap-creator
