apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dapr-shared.fullname" . }}
  labels:
    app: {{ include "dapr-shared.fullname" . }}
data:
    dapr-api-token: {{ .Values.shared.daprd.token | b64enc | quote }}
    {{- if .Values.shared.initContainer.token }}
    app-api-token: {{ .Values.shared.initContainer.token | b64enc | quote }}
    {{- end }}