{{- if .Values.shared.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dapr-shared.serviceAccountName" . }}
  labels:
    {{- include "dapr-shared.labels" . | nindent 4 }}
  {{- with .Values.shared.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
