apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlan-app.configMapName" . }}
  namespace: {{ include "atlan-app.namespace" . }}
  labels:
    {{- include "atlan-app.commonLabels" . | nindent 4 }}
data:
  temporal_host: {{ .Values.temporal.host | quote }}
  temporal_namespace: {{ .Values.temporal.namespace | quote }}
  log_level: {{ .Values.logLevel | quote }}
  central_otel_endpoint: {{ .Values.otel.centralEndpoint | quote }}
  temporal_tls_enabled: {{ .Values.temporal.tls.enabled | quote }}
  temporal_tls_ca_cert_path: {{ .Values.temporal.tls.serverRootCaCertPath | quote }}
  temporal_tls_client_cert_path: {{ .Values.temporal.tls.clientCertPath | quote }}
  temporal_tls_client_key_path: {{ .Values.temporal.tls.clientPrivateKeyPath | quote }}
  temporal_tls_domain: {{ .Values.temporal.tls.domain | quote }}
  auth_enabled: {{ .Values.temporal.auth.enabled | quote }}
