apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlan-app.appName" . }}-dapr-secretstore
  namespace: {{ include "atlan-app.namespace" . }}
  labels:
    {{- include "atlan-app.commonLabels" . | nindent 4 }}
data:
  secretstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: secretstore
    spec:
      type: secretstores.kubernetes
      version: v1
      metadata:
        - name: defaultNamespace
          value: {{ include "atlan-app.namespace" . }}
