apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlan-app.appName" . }}-dapr-eventstore
  namespace: {{ include "atlan-app.namespace" . }}
  labels:
    {{- include "atlan-app.commonLabels" . | nindent 4 }}
data:
  eventstore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: eventstore
    spec:
    {{- if .Values.eventstore.url }}
      type: bindings.http
      version: v1
      metadata:
        - name: url
          value: {{ .Values.eventstore.url }}
    {{- else }}
      type: bindings.localstorage
      version: v1
      ignoreErrors: true
      metadata:
        - name: rootPath
          value: /tmp/local/dapr/eventstore
    {{- end }}
