apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlan-app.handlerName" . }}
  namespace: {{ include "atlan-app.namespace" . }}
  labels:
    {{- include "atlan-app.commonLabels" . | nindent 4 }}
    component: handler
    app.kubernetes.io/component: handler
spec:
  type: ClusterIP
  selector:
    {{- include "atlan-app.handlerSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.handler.port }}
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
