{{- range $name, $cred := .Values.connectorCredentials }}
{{- if $cred.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ include "atlan-app.namespace" $ }}
  labels:
    {{- include "atlan-app.commonLabels" $ | nindent 4 }}
    app.kubernetes.io/component: credential
type: Opaque
stringData:
  {{- $secretData := merge (dict "type" $cred.type) $cred.data }}
  {{- if hasPrefix "atlan" ($cred.type | default "") }}
  {{- $_ := set $secretData "base_url" "INTERNAL" }}
  {{- end }}
  {{ $name }}: {{ $secretData | toJson | quote }}
{{- end }}
{{- end }}
