apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlan-app.serviceAccountName" . }}
  namespace: {{ include "atlan-app.namespace" . }}
  labels:
    {{- include "atlan-app.commonLabels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret.name }}
