"""K003–K010 — generated-artifact freshness and toolkit hygiene.

A repo-level (``scan_all``) check under the **K** series that guards the *outputs*
of ``pkl eval`` (``atlan.yaml``, ``app/generated/**``) and the toolkit dependency
declaration, rather than the ``.pkl`` source that ``legacy_contract`` (K001/K002)
scans.  Multiple check modules under one series letter is the established pattern
(P = ``prescriptions`` + ``determinism``); this rides the existing ``K`` CI leg.

What each rule catches — all **deterministic, no pkl toolchain required**:

* **K003 ContractLockDrift** — ``contract/PklProject`` pins a dependency at an
  exact ``@<version>`` that the resolved lock ``contract/PklProject.deps.json``
  does not match (or the lock is missing / lacks the dependency).
* **K004 MissingGeneratedArtifact** — ``contract/app.pkl`` exists but an expected
  output (``atlan.yaml``, ``app/generated/manifest.json``,
  ``app/generated/_input.py``) is absent — the contract was never generated.
* **K005 GeneratedArtifactBannerStripped** — a generated text artifact is missing
  its ``… DO NOT EDIT …`` provenance banner — a heuristic hand-edit signal.
* **K007 ToolkitVersionOutdated** — the app's ``app-contract-toolkit`` dependency
  resolves (per the lock) to a version below the latest published one.
* **K008 ToolkitSourceNonCanonical** — the toolkit dependency is sourced from a
  base URI other than the canonical SDK-published package.
* **K009 UnresolvedScaffoldPlaceholder** — a generated artifact still contains a
  single-brace scaffold token (``{app_name}``, ``{name}``, …); ``{{…}}`` E2E
  runtime tokens are intentional and excluded.
* **K010 E2EScaffoldingMissing** — a single-entrypoint app is missing the
  generated ``app/generated/_e2e_base.py`` the toolkit always emits for it.

K007/K008 read the canonical base + latest version from the baked-in
``data/toolkit_baseline.json`` (``_toolkit_baseline``): the SDK's toolkit source
is not present in a consumer repo, so the value ships with the wheel and a
drift-guard test keeps it fresh.

Scope
-----
All are ``APP``-scoped and gated on the relevant ``contract/`` file being present,
so they no-op on the SDK (no ``contract/`` at its root) and on any repo that
excludes ``contract/`` from the scan.

Suppression
-----------
Rules anchored on pkl source (``PklProject`` / ``app.pkl``: K003/K004/K007/K008/
K010) reuse the ``// conformance: ignore[...]`` parser from ``legacy_contract``.
Rules anchored on the artifact file (K005/K009) use the ``# conformance:
ignore[...] <reason>`` form (both ``.yaml`` and ``.py`` use ``#``).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from conformance.suite.checks._ast_common import TOOL_VERSION, make_cli_main
from conformance.suite.checks._toolkit_baseline import ToolkitBaseline, load_baseline
from conformance.suite.checks._version import parse_version, version_reached
from conformance.suite.checks.legacy_contract._directives_pkl import (
    _make_pkl_finding_suppressed,
    _parse_pkl_directives,
)
from conformance.suite.schema.findings import Finding

SERIES = "K"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Repo-relative paths of the artifacts every generated app is expected to ship
# (K004). Kept to the outputs that both single- and multi-entrypoint apps emit.
_EXPECTED_OUTPUTS: tuple[str, ...] = (
    "atlan.yaml",
    "app/generated/manifest.json",
    "app/generated/_input.py",
)

# The provenance banner the contract toolkit stamps into every text artifact it
# writes.  Two variants exist in the fleet — "AUTO-GENERATED from contract/app.pkl
# — DO NOT EDIT MANUALLY." and "Generated from contract/app.pkl via
# contract-toolkit. DO NOT EDIT." — so K005 matches the shared invariant: a
# comment in the first few lines that says both "generated" and "do not edit".
_BANNER_GENERATED_RE = re.compile(r"generated", re.IGNORECASE)
_BANNER_DONOTEDIT_RE = re.compile(r"do not edit", re.IGNORECASE)
_BANNER_SCAN_LINES = 5

# ``#``-comment suppression (K005/K009 — both YAML and Python use ``#``).
_HASH_SUPPRESS_RE = re.compile(
    r"#\s*conformance\s*:\s*ignore\s*(?:\[([^\]]*)\])?\s*(.*)",
    re.IGNORECASE,
)

# The pkl dependency-block key an app uses for the toolkit: ``["app-contract-toolkit"]``.
_TOOLKIT_DEP_KEY = "app-contract-toolkit"
_DEP_KEY_RE = re.compile(r'\["([^"]+)"\]')

# K009 — unresolved scaffold placeholder tokens left in a generated artifact.
# Single-brace ``{token}`` the current toolkit resolves at ``pkl eval`` time; a
# literal leftover means the artifact was generated by an outdated toolkit (or a
# legacy base) that never rendered it — e.g. ``{app_name}``, which 0.18.0+ resolves
# to the app's literal name.
#
# Two things are deliberately NOT flagged and must stay out of this set:
#   * ``{{...}}`` — Automation-Engine runtime-substitution tokens (credential,
#     connection, …), resolved at run time. Excluded by the ``(?<!\{)``/``(?!\})``
#     guards.
#   * ``{deployment_name}`` — a deploy-time token the current toolkit STILL emits
#     verbatim into every manifest (task_queue), so it is legitimate, not a
#     leftover. It is absent from the alternation below; do not add it.
_SCAFFOLD_PLACEHOLDER_RE = re.compile(
    r"(?<!\{)\{(?:app_name|app-name|name|entrypoint_name|entrypoint-kebab-name"
    r"|fetch_task_name|connection_name)\}(?!\})"
)

# K010 — E2E scaffolding module that ``pkl eval`` emits for a single-entrypoint app.
_E2E_BASE_OUTPUT = "app/generated/_e2e_base.py"

# A contract that declares an ``entrypoints`` block is a multi-entrypoint bundle;
# its E2E scaffolding lands in per-entrypoint subfolders, so K010 (which requires
# the single-entrypoint _e2e_base.py path) does not apply.
_ENTRYPOINTS_RE = re.compile(r"(?m)^\s*entrypoints\b")


# ---------------------------------------------------------------------------
# Pkl URI parsing (K003)
# ---------------------------------------------------------------------------

_URI_RE = re.compile(r'uri\s*=\s*"([^"]+)"')


def _split_uri(uri: str) -> tuple[str, str] | None:
    """Return ``(scheme-less base, version)`` for a versioned pkl package URI.

    ``package://host/path/pkg@0.16.0`` → ``("host/path/pkg", "0.16.0")``.  The
    scheme is stripped so a ``package://`` pin and a ``projectpackage://`` lock
    entry for the same dependency compare equal.  Returns ``None`` for a URI with
    no ``@<version>`` suffix.
    """
    if "@" not in uri:
        return None
    base, _, version = uri.rpartition("@")
    if not version:
        return None
    # Strip the scheme (everything up to and including "://") if present.
    base = base.split("://", 1)[-1]
    return base, version


def _parse_pkl_project_deps(
    text: str,
) -> list[tuple[str | None, str, str | None, int]]:
    """Return ``[(dep_key, base, version, uri_lineno)]`` for every dependency URI
    in a ``PklProject`` — the single parser behind K003 (version drift) and
    K007/K008 (toolkit floor / source).

    ``dep_key`` is the ``["…"]`` mapping key most recently preceding the ``uri =``
    line (``None`` if the URI has no enclosing key), used to identify the toolkit
    even when its URI points at a non-canonical source.  ``base`` is scheme-less
    (so a ``package://`` pin and a ``projectpackage://`` lock entry compare
    equal); ``version`` is ``None`` for an unversioned URI (e.g. a local
    ``file://`` fork).
    """
    deps: list[tuple[str | None, str, str | None, int]] = []
    current_key: str | None = None
    for lineno, line in enumerate(text.splitlines(), start=1):
        key_m = _DEP_KEY_RE.search(line)
        if key_m is not None:
            current_key = key_m.group(1)
        uri_m = _URI_RE.search(line)
        if uri_m is None:
            continue
        split = _split_uri(uri_m.group(1))
        if split is not None:
            base, version = split
        else:
            base, version = uri_m.group(1).split("://", 1)[-1], None
        deps.append((current_key, base, version, lineno))
        current_key = None
    return deps


def _parse_deps_lock(text: str) -> dict[str, str] | None:
    """Return ``{base: resolved_version}`` from a ``PklProject.deps.json`` lock,
    or ``None`` when the file is not valid JSON (compare is then skipped)."""
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    resolved: dict[str, str] = {}
    deps = data.get("resolvedDependencies")
    if not isinstance(deps, dict):
        return {}
    for entry in deps.values():
        if not isinstance(entry, dict):
            continue
        uri = entry.get("uri")
        if not isinstance(uri, str):
            continue
        split = _split_uri(uri)
        if split is not None:
            resolved[split[0]] = split[1]
    return resolved


def _version_satisfied(pin: str, resolved: str) -> bool:
    """True when *resolved* is compatible with the *pin* (prefix match).

    A broad pin (``0`` or ``0.16``) is satisfied by any resolved version that
    extends it (``0.16.0``); only a fully-specified pin that disagrees is drift.
    """
    pin_parts = pin.split(".")
    resolved_parts = resolved.split(".")
    return resolved_parts[: len(pin_parts)] == pin_parts


# ---------------------------------------------------------------------------
# Toolkit dependency selection (K007/K008)
# ---------------------------------------------------------------------------


def _find_toolkit_dep(
    deps: list[tuple[str | None, str, str | None, int]],
) -> tuple[str, str | None, int] | None:
    """Return ``(base, version, lineno)`` for the app-contract-toolkit dependency.

    Identified by the ``["app-contract-toolkit"]`` mapping key first (the name an
    app amends via ``@app-contract-toolkit/App.pkl``), falling back to any URI
    whose path segment is ``app-contract-toolkit`` — so a dep pointed at a fork
    under a different key is still recognised as the toolkit.
    """
    for key, base, version, lineno in deps:
        if key == _TOOLKIT_DEP_KEY or base.rstrip("/").endswith(f"/{_TOOLKIT_DEP_KEY}"):
            return base, version, lineno
    return None


def _resolved_toolkit_version(root: Path, base: str) -> str | None:
    """Return the version the lock resolved for *base*, or ``None`` when the lock
    is absent/unparseable/does not carry the dependency."""
    deps_path = root / "contract" / "PklProject.deps.json"
    if not deps_path.is_file():
        return None
    try:
        lock = _parse_deps_lock(deps_path.read_text(encoding="utf-8"))
    except OSError:
        return None
    if not lock:
        return None
    return lock.get(base)


def _scan_toolkit_dependency(
    root: Path, present: set[str], baseline: ToolkitBaseline | None
) -> list[Finding]:
    """K007/K008 — the app's toolkit dependency must come from the canonical
    source (K008) and be at/above the latest published version (K007)."""
    if baseline is None or "contract/PklProject" not in present:
        return []
    pkl_project = root / "contract" / "PklProject"
    try:
        text = pkl_project.read_text(encoding="utf-8")
    except OSError:
        return []

    toolkit = _find_toolkit_dep(_parse_pkl_project_deps(text))
    if toolkit is None:
        return []
    base, _pin_version, lineno = toolkit

    directives = _parse_pkl_directives(text)
    rel = "contract/PklProject"

    if base != baseline.canonical_base:
        suppressed, justification = _make_pkl_finding_suppressed(
            rule_id="K008", line=lineno, directives=directives
        )
        return [
            Finding(
                rule_id="K008",
                file=rel,
                line=lineno,
                column=1,
                message=(
                    f"app-contract-toolkit is sourced from '{base}' instead of the "
                    f"canonical '{baseline.canonical_base}'. Point the dependency at "
                    f"the SDK-published package "
                    f"'package://{baseline.canonical_base}@{baseline.latest_version}' "
                    f"and re-run 'pkl project resolve'. "
                    f"Suppress with: // conformance: ignore[K008] <reason>"
                ),
                snippet=None,
                suppressed=suppressed,
                suppression_justification=justification,
            )
        ]

    # Canonical source: use the resolved lock as the ground truth for the version
    # actually in use.  A missing/stale lock is K003's concern, so K007 stays quiet
    # rather than guessing from a broad pin (e.g. ``@0``).
    resolved = _resolved_toolkit_version(root, base)
    if resolved is None:
        return []
    current = parse_version(resolved)
    latest = parse_version(baseline.latest_version)
    if current is None or latest is None or version_reached(latest, current):
        return []

    suppressed, justification = _make_pkl_finding_suppressed(
        rule_id="K007", line=lineno, directives=directives
    )
    return [
        Finding(
            rule_id="K007",
            file=rel,
            line=lineno,
            column=1,
            message=(
                f"app-contract-toolkit resolves to '{resolved}' but the latest "
                f"published version is '{baseline.latest_version}'. Bump the pin in "
                f"contract/PklProject, run 'pkl project resolve', then regenerate "
                f"with 'pkl eval -m . contract/app.pkl'. An outdated toolkit is the "
                f"usual root cause of stale generated artifacts and leftover "
                f"placeholders (K009). "
                f"Suppress with: // conformance: ignore[K007] <reason>"
            ),
            snippet=None,
            suppressed=suppressed,
            suppression_justification=justification,
        )
    ]


# ---------------------------------------------------------------------------
# K005 banner / suppression helpers
# ---------------------------------------------------------------------------


def _has_banner(text: str) -> bool:
    """True when a single header line carries both provenance markers.

    Requiring both markers on the *same* line (rather than anywhere in the
    header window) avoids a false positive on a hand-written preamble that
    happens to mention "generated" and "do not edit" on separate lines.
    """
    lines = text.splitlines()[:_BANNER_SCAN_LINES]
    return any(
        _BANNER_GENERATED_RE.search(line) and _BANNER_DONOTEDIT_RE.search(line)
        for line in lines
    )


def _match_hash_directive(line: str, rule_id: str) -> str | None:
    """Return the justification for a ``# conformance: ignore`` directive on *line*
    that applies to *rule_id*, or ``None``.

    Searches the whole line rather than anchoring on the first ``#`` so a directive
    following an earlier ``#`` (e.g. a URL fragment in a YAML value) is still
    honoured. A directive with no justification text is rejected — it never
    silently suppresses.
    """
    m = _HASH_SUPPRESS_RE.search(line)
    if m is None:
        return None
    justification = m.group(2).strip()
    if not justification:
        return None
    ids = {s.strip() for s in (m.group(1) or "").split(",") if s.strip()}
    if not ids or rule_id in ids:
        return justification
    return None


def _hash_suppressed(text: str, rule_id: str) -> tuple[bool, str | None]:
    """Return ``(suppressed, justification)`` for a ``#``-comment directive in the
    file header (K005 anchors on line 1, so only the header can suppress it)."""
    for line in text.splitlines()[: _BANNER_SCAN_LINES + 1]:
        justification = _match_hash_directive(line, rule_id)
        if justification is not None:
            return True, justification
    return False, None


# ---------------------------------------------------------------------------
# Per-rule scans
# ---------------------------------------------------------------------------


def _scan_lock_drift(root: Path, present: set[str]) -> list[Finding]:
    """K003 — compare ``contract/PklProject`` pins against the resolved lock."""
    if "contract/PklProject" not in present:
        return []
    pkl_project = root / "contract" / "PklProject"
    try:
        text = pkl_project.read_text(encoding="utf-8")
    except OSError:
        return []
    pins = [
        (base, version, lineno)
        for _key, base, version, lineno in _parse_pkl_project_deps(text)
        if version is not None
    ]
    if not pins:
        return []

    directives = _parse_pkl_directives(text)
    rel = "contract/PklProject"
    findings: list[Finding] = []

    deps_path = root / "contract" / "PklProject.deps.json"
    lock: dict[str, str] | None = None
    if deps_path.is_file():
        try:
            lock = _parse_deps_lock(deps_path.read_text(encoding="utf-8"))
        except OSError:
            lock = None

    for base, version, lineno in pins:
        if lock is None:
            message = (
                f"contract/PklProject pins '{base}@{version}' but the resolved "
                f"lock contract/PklProject.deps.json is missing or unparseable. "
                f"Run 'pkl project resolve' to regenerate the lock, then "
                f"'pkl eval -m . contract/app.pkl' to regenerate the artifacts. "
                f"Suppress with: // conformance: ignore[K003] <reason>"
            )
        else:
            resolved = lock.get(base)
            if resolved is None:
                message = (
                    f"contract/PklProject pins '{base}@{version}' but the "
                    f"dependency is absent from the resolved lock "
                    f"contract/PklProject.deps.json. Run 'pkl project resolve'. "
                    f"Suppress with: // conformance: ignore[K003] <reason>"
                )
            elif not _version_satisfied(version, resolved):
                message = (
                    f"contract/PklProject pins '{base}@{version}' but the lock "
                    f"contract/PklProject.deps.json resolved '@{resolved}'. The "
                    f"generated artifacts were built from the stale version. Run "
                    f"'pkl project resolve' then regenerate. "
                    f"Suppress with: // conformance: ignore[K003] <reason>"
                )
            else:
                continue

        suppressed, justification = _make_pkl_finding_suppressed(
            rule_id="K003", line=lineno, directives=directives
        )
        findings.append(
            Finding(
                rule_id="K003",
                file=rel,
                line=lineno,
                column=1,
                message=message,
                snippet=None,
                suppressed=suppressed,
                suppression_justification=justification,
            )
        )
    return findings


def _amends_line(text: str) -> int:
    """Return the 1-based line of the ``amends`` statement, or 1 if absent."""
    for lineno, line in enumerate(text.splitlines(), start=1):
        if line.lstrip().startswith("amends"):
            return lineno
    return 1


def _scan_missing_outputs(root: Path, present: set[str]) -> list[Finding]:
    """K004 — flag expected generated outputs that are absent while the contract
    exists."""
    if "contract/app.pkl" not in present:
        return []
    app_pkl = root / "contract" / "app.pkl"
    try:
        text = app_pkl.read_text(encoding="utf-8")
    except OSError:
        return []

    directives = _parse_pkl_directives(text)
    anchor = _amends_line(text)
    rel = "contract/app.pkl"
    findings: list[Finding] = []

    for expected in _EXPECTED_OUTPUTS:
        if (root / expected).is_file():
            continue
        suppressed, justification = _make_pkl_finding_suppressed(
            rule_id="K004", line=anchor, directives=directives
        )
        findings.append(
            Finding(
                rule_id="K004",
                file=rel,
                line=anchor,
                column=1,
                message=(
                    f"contract/app.pkl exists but the expected generated artifact "
                    f"'{expected}' is missing. Regenerate with "
                    f"'pkl eval -m . contract/app.pkl' and commit the result. "
                    f"Suppress with: // conformance: ignore[K004] <reason>"
                ),
                snippet=None,
                suppressed=suppressed,
                suppression_justification=justification,
            )
        )
    return findings


def _is_banner_bearing(rel: str) -> bool:
    """True for a generated text artifact expected to carry a provenance banner.

    ``atlan.yaml`` / ``app.yaml`` at the repo root, and any ``.py`` under
    ``app/generated/`` other than the (empty) ``__init__.py``.  ``.json`` outputs
    are excluded — JSON has no comment syntax to carry a banner.
    """
    if rel in ("atlan.yaml", "app.yaml"):
        return True
    if not rel.startswith("app/generated/"):
        return False
    if not rel.endswith(".py"):
        return False
    return Path(rel).name != "__init__.py"


def _scan_banners(root: Path, present: set[str]) -> list[Finding]:
    """K005 — flag banner-bearing generated artifacts whose banner is missing."""
    if "contract/app.pkl" not in present:
        return []
    findings: list[Finding] = []
    for rel in sorted(present):
        if "__pycache__" in rel or not _is_banner_bearing(rel):
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if _has_banner(text):
            continue
        suppressed, justification = _hash_suppressed(text, "K005")
        findings.append(
            Finding(
                rule_id="K005",
                file=rel,
                line=1,
                column=1,
                message=(
                    f"Generated artifact '{rel}' is missing its "
                    f"'DO NOT EDIT' provenance banner — it was likely hand-authored "
                    f"or hand-edited and will drift from the contract on the next "
                    f"regeneration. Regenerate with 'pkl eval -m . contract/app.pkl', "
                    f"or if this file is intentionally hand-maintained, suppress "
                    f"with: # conformance: ignore[K005] <reason>"
                ),
                snippet=None,
                suppressed=suppressed,
                suppression_justification=justification,
            )
        )
    return findings


# ---------------------------------------------------------------------------
# K009 placeholder / K010 E2E scaffolding
# ---------------------------------------------------------------------------


def _line_hash_suppressed(
    lines: list[str], lineno: int, rule_id: str
) -> tuple[bool, str | None]:
    """Return ``(suppressed, justification)`` for a ``#``-comment directive on the
    finding's own line or the comment-only line directly above it."""
    for check_line in (lineno, lineno - 1):
        if check_line < 1 or check_line > len(lines):
            continue
        raw = lines[check_line - 1]
        if check_line == lineno - 1 and raw.lstrip()[:1] != "#":
            # A trailing inline directive on a content line must not absorb the
            # finding on the following line.
            continue
        justification = _match_hash_directive(raw, rule_id)
        if justification is not None:
            return True, justification
    return False, None


def _is_generated_artifact(rel: str) -> bool:
    """True for a committed ``pkl eval`` output that should never carry a
    leftover scaffold placeholder — ``atlan.yaml`` / ``app.yaml`` and anything
    under ``app/generated/``."""
    return rel in ("atlan.yaml", "app.yaml") or rel.startswith("app/generated/")


def _scan_placeholders(root: Path, present: set[str]) -> list[Finding]:
    """K009 — flag unresolved scaffold placeholder tokens in generated artifacts."""
    if "contract/app.pkl" not in present:
        return []
    findings: list[Finding] = []
    for rel in sorted(present):
        if "__pycache__" in rel or not _is_generated_artifact(rel):
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            # ``app/generated/`` can hold non-text blobs (e.g. a stray binary or
            # .DS_Store); skip them rather than crash the whole suite run.
            continue
        lines = text.splitlines()
        for i, line in enumerate(lines, start=1):
            for m in _SCAFFOLD_PLACEHOLDER_RE.finditer(line):
                suppressed, justification = _line_hash_suppressed(lines, i, "K009")
                findings.append(
                    Finding(
                        rule_id="K009",
                        file=rel,
                        line=i,
                        column=m.start() + 1,
                        message=(
                            f"Generated artifact '{rel}' contains the unresolved "
                            f"scaffold placeholder '{m.group(0)}' — the current toolkit "
                            f"renders this to a literal value, so the artifact was "
                            f"generated by an outdated toolkit or a legacy NativeApp.pkl "
                            f"base and is wrong as shipped. Upgrade app-contract-toolkit "
                            f"to the latest version (and migrate to App.pkl if still on "
                            f"NativeApp.pkl), then regenerate with "
                            f"'pkl eval -m . contract/app.pkl'. "
                            f"Suppress with: # conformance: ignore[K009] <reason>"
                        ),
                        snippet=None,
                        suppressed=suppressed,
                        suppression_justification=justification,
                    )
                )
    return findings


def _scan_e2e_scaffolding(root: Path, present: set[str]) -> list[Finding]:
    """K010 — a single-entrypoint app must ship the generated ``_e2e_base.py``."""
    if "contract/app.pkl" not in present:
        return []
    app_pkl = root / "contract" / "app.pkl"
    try:
        text = app_pkl.read_text(encoding="utf-8")
    except OSError:
        return []
    if _ENTRYPOINTS_RE.search(text):
        # Multi-entrypoint bundle: E2E scaffolding lands per-entrypoint, not at the
        # single-entrypoint _e2e_base.py path — out of scope for K010.
        return []
    if _E2E_BASE_OUTPUT in present:
        return []

    directives = _parse_pkl_directives(text)
    anchor = _amends_line(text)
    suppressed, justification = _make_pkl_finding_suppressed(
        rule_id="K010", line=anchor, directives=directives
    )
    return [
        Finding(
            rule_id="K010",
            file="contract/app.pkl",
            line=anchor,
            column=1,
            message=(
                f"contract/app.pkl exists but the generated E2E scaffolding "
                f"'{_E2E_BASE_OUTPUT}' is missing. The toolkit emits it for every "
                f"single-entrypoint app; regenerate with "
                f"'pkl eval -m . contract/app.pkl' and commit the result. "
                f"Suppress with: // conformance: ignore[K010] <reason>"
            ),
            snippet=None,
            suppressed=suppressed,
            suppression_justification=justification,
        )
    ]


# ---------------------------------------------------------------------------
# Scan API
# ---------------------------------------------------------------------------


def scan_all(paths: list[Path], root: Path) -> list[Finding]:
    """Run the K003–K010 generated-artifact / toolkit rules over *paths*.

    ``paths`` is the post-exclusion discovery list; membership gates each rule so
    excluding ``contract/`` disables the whole check for a repo.
    """
    present: set[str] = set()
    for p in paths:
        try:
            present.add(p.relative_to(root).as_posix())
        except ValueError:
            continue
    baseline = load_baseline()
    findings: list[Finding] = []
    findings.extend(_scan_lock_drift(root, present))
    findings.extend(_scan_missing_outputs(root, present))
    findings.extend(_scan_banners(root, present))
    findings.extend(_scan_toolkit_dependency(root, present, baseline))
    findings.extend(_scan_placeholders(root, present))
    findings.extend(_scan_e2e_scaffolding(root, present))
    return findings


def scan_path(path: Path, root: Path) -> list[Finding]:
    """Single-path shim so the registration satisfies ``CheckRegistration``.

    K003/K004/K005 are inherently repo-level; scanning a lone file routes through
    :func:`scan_all` with that one path.
    """
    return scan_all([path], root)


def discover(root: Path) -> list[Path]:
    """Return the contract source + generated artifacts under *root*.

    Only the repo-root ``contract/``, ``atlan.yaml`` / ``app.yaml``, and
    ``app/generated/`` are considered — the app layout — so nested toolkit
    examples in the SDK are never scanned (and APP scope drops them anyway).
    """
    out: list[Path] = []
    contract = root / "contract"
    for name in ("PklProject", "PklProject.deps.json", "app.pkl"):
        candidate = contract / name
        if candidate.is_file():
            out.append(candidate)
    for name in ("atlan.yaml", "app.yaml"):
        candidate = root / name
        if candidate.is_file():
            out.append(candidate)
    generated = root / "app" / "generated"
    if generated.is_dir():
        out.extend(p for p in sorted(generated.rglob("*")) if p.is_file())
    return out


main = make_cli_main(
    scan_all=scan_all,
    description=(
        "K003/K004/K005 generated-artifact freshness: flag a stale Pkl lock "
        "(PklProject vs PklProject.deps.json), missing generated outputs, or a "
        "generated artifact whose provenance banner has been stripped (BLDX-1414)."
    ),
    discover=discover,
    default_scan_paths=(".",),
    default_tool_version=TOOL_VERSION,
)
"""CLI entry point for the generated-artifact freshness check."""


if __name__ == "__main__":
    sys.exit(main())
