---
repositories:
- name: dapr
  url: https://dapr.github.io/helm-charts/
- name: cloudnative-pg
  url: https://cloudnative-pg.github.io/charts
- name: temporal-operator
  url: https://alexandrevilain.github.io/temporal-operator
- name: cert-manager
  url: https://charts.jetstack.io
- name: minio
  url: https://operator.min.io

---
# Define default values for global configurations
environments:
  default:
    values:
      - singleNamespace:
          enabled: false
      - releaseNamespaces:
          dapr: atlan-dapr
          daprShared: atlan-dapr-shared
          cloudnativePg: atlan-cloudnative-pg
          postgresCluster: atlan-postgres
          certManager: atlan-cert-manager
          temporalOperator: atlan-temporal-operator
          minioOperator: atlan-minio-operator
          minioTenant: atlan-minio-tenant
      - enableMinio:
          enabled: false
      - enableDaprDashboard:
          enabled: false
      - enableDaprInjected:
          enabled: true

  unified:
    values:
      - singleNamespace:
          enabled: true
      - releaseNamespaces:
          namespace: atlan-secure-agent
      - enableMinio:
          enabled: false
      - enableDaprDashboard:
          enabled: false
      - enableDaprInjected:
          enabled: true

---
releases:
- name: dapr
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.dapr }}{{ end }}'
  createNamespace: true
  chart: dapr/dapr
  version: 1.14.4
  disableValidation: true
  missingFileHandler: Error
  values:
    - values/dapr.yaml
    - dapr_sidecar_injector:
        enabled: {{ .Environment.Values.enableDaprInjected.enabled }}

- name: dapr-dashboard
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.dapr }}{{ end }}'
  createNamespace: true
  chart: dapr/dapr-dashboard
  version: 0.15.0
  disableValidation: true
  installed: {{ .Environment.Values.enableDaprDashboard.enabled }}
  missingFileHandler: Error
  values:
    - values/dapr_dashboard.yaml

- name: cloudnative-pg
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.cloudnativePg }}{{ end }}'
  createNamespace: true
  chart: cloudnative-pg/cloudnative-pg
  version: 0.22.1
  disableValidation: true
  wait: true  # Wait for cloudnative-pg to be ready
  values:
    - values/cloudnative_pg.yaml

- name: postgres-cluster
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.postgresCluster }}{{ end }}'
  createNamespace: true
  chart: cloudnative-pg/cluster
  version: 0.1.0
  disableValidation: true
  wait: true  # Wait for postgres-cluster to be ready
  values:
    - values/cloudnative_pg_cluster.yaml
  needs:
    - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/cloudnative-pg{{ else }}{{ .Environment.Values.releaseNamespaces.cloudnativePg }}/cloudnative-pg{{ end }}' # Ensure cloudnative-pg is deployed before postgres-cluster

- name: cert-manager
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.certManager }}{{ end }}'
  createNamespace: true
  chart: cert-manager/cert-manager
  version: 1.16.1
  disableValidation: true
  wait: true  # Wait for cert-manager to be ready
  values:
    - values/cert_manager.yaml

- name: temporal-operator
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.temporalOperator }}{{ end }}'
  createNamespace: true
  chart: temporal-operator/temporal-operator
  version: 0.5.0
  disableValidation: true
  wait: true  # Wait for temporal-operator to be ready
  values:
    - values/temporal_operator.yaml
  needs:
    - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/cert-manager{{ else }}{{ .Environment.Values.releaseNamespaces.certManager }}/cert-manager{{ end }}' # Ensure cert-manager is deployed before temporal

- name: minio-operator
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.minioOperator }}{{ end }}'
  createNamespace: true
  chart: minio/operator
  version: 6.0.4
  disableValidation: true
  installed: {{ .Environment.Values.enableMinio.enabled }}
  wait: true  # Wait for minio-operator to be ready
  values:
    - values/minio_operator.yaml

- name: minio-tenant
  namespace: '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}{{ else }}{{ .Environment.Values.releaseNamespaces.minioTenant }}{{ end }}'
  createNamespace: true
  chart: minio/tenant
  version: 6.0.4
  disableValidation: true
  installed: {{ .Environment.Values.enableMinio.enabled }}
  values:
    - values/minio_tenant.yaml
  needs:
    - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/minio-operator{{ else }}{{ .Environment.Values.releaseNamespaces.minioOperator }}/minio-operator{{ end }}' # Ensure minio-operator is deployed before tenant

# - name: atlan-app-components
#   chart: "."
#   version: 0.1.0
#   disableValidation: true
#   values:
#     - values.yaml
#   needs:
#     - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/dapr{{ else }}{{ .Environment.Values.releaseNamespaces.dapr }}/dapr{{ end }}' # Ensure dapr is deployed before atlan-app-components
#     - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/postgres-cluster{{ else }}{{ .Environment.Values.releaseNamespaces.postgresCluster }}/postgres-cluster{{ end }}' # Ensure postgres-cluster is deployed before atlan-app-components
#     - '{{ if .Environment.Values.singleNamespace.enabled }}{{ .Environment.Values.releaseNamespaces.namespace }}/temporal-operator{{ else }}{{ .Environment.Values.releaseNamespaces.temporalOperator }}/temporal-operator{{ end }}' # Ensure temporal-operator is deployed before atlan-app-components
