"""Deprecated alias of :mod:`application_sdk_api.handler` (removal in v4.0).

The handler surface lives in the ``atlan-application-sdk-api`` package so the
consolidated API host can serve an app's handler without this distribution.
Import from ``application_sdk_api.handler`` instead. Every name here resolves to the object
in the api package, so behaviour is unchanged; handler names warn.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING as _TYPE_CHECKING
from typing import Any as _Any

from application_sdk_api.handler import (  # noqa: F401 — worker-surface, not deprecated
    CloudEventEnvelope,
    EventFilterRule,
    EventTriggerConfig,
    FileUploadResponse,
    PreflightGateMode,
    SubscriptionConfig,
)

from application_sdk.handler.service import (  # noqa: F401 — not handler surface; not deprecated here
    create_app_handler_service,
    run_app_handler_service,
)

if _TYPE_CHECKING:
    from application_sdk_api.handler import (  # noqa: F401
        ApiMetadataObject,
        ApiMetadataOutput,
        AuthInput,
        AuthOutput,
        AuthStatus,
        BaseConnectionConfig,
        BaseMetadataConfig,
        DefaultHandler,
        Handler,
        HandlerContext,
        HandlerCredential,
        HandlerError,
        MetadataInput,
        MetadataOutput,
        PreflightCheck,
        PreflightInput,
        PreflightOutput,
        PreflightStatus,
        SqlMetadataObject,
        SqlMetadataOutput,
        flatten_credentials_to_pairs,
        normalize_credentials,
        unverifiable_preflight_result,
    )

#: Handler-surface names, served with a DeprecationWarning (removal in v4.0).
_DEPRECATED_CONSTANTS: dict[str, str] = {
    "ApiMetadataObject": "application_sdk_api.handler.ApiMetadataObject",
    "ApiMetadataOutput": "application_sdk_api.handler.ApiMetadataOutput",
    "AuthInput": "application_sdk_api.handler.AuthInput",
    "AuthOutput": "application_sdk_api.handler.AuthOutput",
    "AuthStatus": "application_sdk_api.handler.AuthStatus",
    "BaseConnectionConfig": "application_sdk_api.handler.BaseConnectionConfig",
    "BaseMetadataConfig": "application_sdk_api.handler.BaseMetadataConfig",
    "DefaultHandler": "application_sdk_api.handler.DefaultHandler",
    "Handler": "application_sdk_api.handler.Handler",
    "HandlerContext": "application_sdk_api.handler.HandlerContext",
    "HandlerCredential": "application_sdk_api.handler.HandlerCredential",
    "HandlerError": "application_sdk_api.handler.HandlerError",
    "MetadataInput": "application_sdk_api.handler.MetadataInput",
    "MetadataOutput": "application_sdk_api.handler.MetadataOutput",
    "PreflightCheck": "application_sdk_api.handler.PreflightCheck",
    "PreflightInput": "application_sdk_api.handler.PreflightInput",
    "PreflightOutput": "application_sdk_api.handler.PreflightOutput",
    "PreflightStatus": "application_sdk_api.handler.PreflightStatus",
    "SqlMetadataObject": "application_sdk_api.handler.SqlMetadataObject",
    "SqlMetadataOutput": "application_sdk_api.handler.SqlMetadataOutput",
    "flatten_credentials_to_pairs": "application_sdk_api.handler.flatten_credentials_to_pairs",
    "normalize_credentials": "application_sdk_api.handler.normalize_credentials",
    "unverifiable_preflight_result": "application_sdk_api.handler.unverifiable_preflight_result",
}

__all__ = [
    "ApiMetadataObject",
    "ApiMetadataOutput",
    "AuthInput",
    "AuthOutput",
    "AuthStatus",
    "BaseConnectionConfig",
    "BaseMetadataConfig",
    "CloudEventEnvelope",
    "DefaultHandler",
    "EventFilterRule",
    "EventTriggerConfig",
    "FileUploadResponse",
    "Handler",
    "HandlerContext",
    "HandlerCredential",
    "HandlerError",
    "MetadataInput",
    "MetadataOutput",
    "PreflightCheck",
    "PreflightGateMode",
    "PreflightInput",
    "PreflightOutput",
    "PreflightStatus",
    "SqlMetadataObject",
    "SqlMetadataOutput",
    "SubscriptionConfig",
    "create_app_handler_service",
    "flatten_credentials_to_pairs",
    "normalize_credentials",
    "run_app_handler_service",
    "unverifiable_preflight_result",
]


def __getattr__(name: str) -> _Any:
    target = _DEPRECATED_CONSTANTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, _, attr = target.rpartition(".")
    _warnings.warn(
        f"application_sdk.handler.{name} is deprecated and will be removed in v4.0; "
        f"import it from {module}",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
