"""Deprecated alias of :mod:`application_sdk_api.handler.base` (removal in v4.0).

The handler surface lives in the ``atlan-application-sdk-api`` package so the
consolidated API host can serve an app's handler without this distribution.
Import from ``application_sdk_api.handler.base`` instead. Every name here resolves to the object
in the api package, so behaviour is unchanged; handler names warn.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING as _TYPE_CHECKING
from typing import Any as _Any

if _TYPE_CHECKING:
    from application_sdk_api.handler.base import (  # noqa: F401
        HANDLER_ERROR,
        AppError,
        AuthInput,
        AuthOutput,
        AuthStatus,
        DefaultHandler,
        ErrorCode,
        Handler,
        HandlerError,
        MetadataInput,
        MetadataOutput,
        PreflightInput,
        PreflightOutput,
        PreflightStatus,
        SqlMetadataOutput,
        get_handler_context,
    )

#: Handler-surface names, served with a DeprecationWarning (removal in v4.0).
_DEPRECATED_CONSTANTS: dict[str, str] = {
    "HANDLER_ERROR": "application_sdk_api.handler.base.HANDLER_ERROR",
    "AppError": "application_sdk_api.handler.base.AppError",
    "AuthInput": "application_sdk_api.handler.base.AuthInput",
    "AuthOutput": "application_sdk_api.handler.base.AuthOutput",
    "AuthStatus": "application_sdk_api.handler.base.AuthStatus",
    "DefaultHandler": "application_sdk_api.handler.base.DefaultHandler",
    "ErrorCode": "application_sdk_api.handler.base.ErrorCode",
    "Handler": "application_sdk_api.handler.base.Handler",
    "HandlerError": "application_sdk_api.handler.base.HandlerError",
    "MetadataInput": "application_sdk_api.handler.base.MetadataInput",
    "MetadataOutput": "application_sdk_api.handler.base.MetadataOutput",
    "PreflightInput": "application_sdk_api.handler.base.PreflightInput",
    "PreflightOutput": "application_sdk_api.handler.base.PreflightOutput",
    "PreflightStatus": "application_sdk_api.handler.base.PreflightStatus",
    "SqlMetadataOutput": "application_sdk_api.handler.base.SqlMetadataOutput",
    "get_handler_context": "application_sdk_api.handler.base.get_handler_context",
}

__all__ = [
    "AppError",
    "AuthInput",
    "AuthOutput",
    "AuthStatus",
    "DefaultHandler",
    "ErrorCode",
    "HANDLER_ERROR",
    "Handler",
    "HandlerError",
    "MetadataInput",
    "MetadataOutput",
    "PreflightInput",
    "PreflightOutput",
    "PreflightStatus",
    "SqlMetadataOutput",
    "get_handler_context",
]


def __getattr__(name: str) -> _Any:
    target = _DEPRECATED_CONSTANTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, _, attr = target.rpartition(".")
    _warnings.warn(
        f"application_sdk.handler.base.{name} is deprecated and will be removed in v4.0; "
        f"import it from {module}",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
