"""Deprecated alias of :mod:`application_sdk_api.handler.contracts` (removal in v4.0).

The handler surface lives in the ``atlan-application-sdk-api`` package so the
consolidated API host can serve an app's handler without this distribution.
Import from ``application_sdk_api.handler.contracts`` instead. Every name here resolves to the object
in the api package, so behaviour is unchanged; handler names warn.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING as _TYPE_CHECKING
from typing import Any as _Any

from application_sdk_api.handler.contracts import (  # noqa: F401 — worker-surface, not deprecated
    CloudEventEnvelope,
    EventFilterRule,
    EventTriggerConfig,
    FileUploadResponse,
    PreflightGateMode,
    SubscriptionConfig,
)

if _TYPE_CHECKING:
    from application_sdk_api.handler.contracts import (  # noqa: F401
        AUTH_STATUS_HTTP_CODES,
        UNVERIFIABLE_CHECK_NAME,
        AgentCredentialSpec,
        ApiMetadataObject,
        ApiMetadataOutput,
        AppError,
        AuthInput,
        AuthOutput,
        AuthStatus,
        BaseConnectionConfig,
        BaseMetadataConfig,
        FailureDetails,
        HandlerCredential,
        InternalError,
        MetadataInput,
        MetadataOutput,
        PreflightCheck,
        PreflightInput,
        PreflightOutput,
        PreflightStatus,
        SerializableEnum,
        SqlMetadataObject,
        SqlMetadataOutput,
        flatten_credentials_to_pairs,
        get_logger,
        logger,
        normalize_credentials,
        parse_credentials_extra,
        redact_secrets,
        sanitize_cause_repr,
        unverifiable_preflight_result,
    )

#: Handler-surface names, served with a DeprecationWarning (removal in v4.0).
_DEPRECATED_CONSTANTS: dict[str, str] = {
    "AUTH_STATUS_HTTP_CODES": "application_sdk_api.handler.contracts.AUTH_STATUS_HTTP_CODES",
    "UNVERIFIABLE_CHECK_NAME": "application_sdk_api.handler.contracts.UNVERIFIABLE_CHECK_NAME",
    "AgentCredentialSpec": "application_sdk_api.handler.contracts.AgentCredentialSpec",
    "ApiMetadataObject": "application_sdk_api.handler.contracts.ApiMetadataObject",
    "ApiMetadataOutput": "application_sdk_api.handler.contracts.ApiMetadataOutput",
    "AppError": "application_sdk_api.handler.contracts.AppError",
    "AuthInput": "application_sdk_api.handler.contracts.AuthInput",
    "AuthOutput": "application_sdk_api.handler.contracts.AuthOutput",
    "AuthStatus": "application_sdk_api.handler.contracts.AuthStatus",
    "BaseConnectionConfig": "application_sdk_api.handler.contracts.BaseConnectionConfig",
    "BaseMetadataConfig": "application_sdk_api.handler.contracts.BaseMetadataConfig",
    "FailureDetails": "application_sdk_api.handler.contracts.FailureDetails",
    "HandlerCredential": "application_sdk_api.handler.contracts.HandlerCredential",
    "InternalError": "application_sdk_api.handler.contracts.InternalError",
    "MetadataInput": "application_sdk_api.handler.contracts.MetadataInput",
    "MetadataOutput": "application_sdk_api.handler.contracts.MetadataOutput",
    "PreflightCheck": "application_sdk_api.handler.contracts.PreflightCheck",
    "PreflightInput": "application_sdk_api.handler.contracts.PreflightInput",
    "PreflightOutput": "application_sdk_api.handler.contracts.PreflightOutput",
    "PreflightStatus": "application_sdk_api.handler.contracts.PreflightStatus",
    "SerializableEnum": "application_sdk_api.handler.contracts.SerializableEnum",
    "SqlMetadataObject": "application_sdk_api.handler.contracts.SqlMetadataObject",
    "SqlMetadataOutput": "application_sdk_api.handler.contracts.SqlMetadataOutput",
    "flatten_credentials_to_pairs": "application_sdk_api.handler.contracts.flatten_credentials_to_pairs",
    "get_logger": "application_sdk_api.handler.contracts.get_logger",
    "logger": "application_sdk_api.handler.contracts.logger",
    "normalize_credentials": "application_sdk_api.handler.contracts.normalize_credentials",
    "parse_credentials_extra": "application_sdk_api.handler.contracts.parse_credentials_extra",
    "redact_secrets": "application_sdk_api.handler.contracts.redact_secrets",
    "sanitize_cause_repr": "application_sdk_api.handler.contracts.sanitize_cause_repr",
    "unverifiable_preflight_result": "application_sdk_api.handler.contracts.unverifiable_preflight_result",
}

__all__ = [
    "AUTH_STATUS_HTTP_CODES",
    "AgentCredentialSpec",
    "ApiMetadataObject",
    "ApiMetadataOutput",
    "AppError",
    "AuthInput",
    "AuthOutput",
    "AuthStatus",
    "BaseConnectionConfig",
    "BaseMetadataConfig",
    "CloudEventEnvelope",
    "EventFilterRule",
    "EventTriggerConfig",
    "FailureDetails",
    "FileUploadResponse",
    "HandlerCredential",
    "InternalError",
    "MetadataInput",
    "MetadataOutput",
    "PreflightCheck",
    "PreflightGateMode",
    "PreflightInput",
    "PreflightOutput",
    "PreflightStatus",
    "SerializableEnum",
    "SqlMetadataObject",
    "SqlMetadataOutput",
    "SubscriptionConfig",
    "UNVERIFIABLE_CHECK_NAME",
    "flatten_credentials_to_pairs",
    "get_logger",
    "logger",
    "normalize_credentials",
    "parse_credentials_extra",
    "redact_secrets",
    "sanitize_cause_repr",
    "unverifiable_preflight_result",
]


def __getattr__(name: str) -> _Any:
    target = _DEPRECATED_CONSTANTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, _, attr = target.rpartition(".")
    _warnings.warn(
        f"application_sdk.handler.contracts.{name} is deprecated and will be removed in v4.0; "
        f"import it from {module}",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
