"""Deprecated alias of :mod:`application_sdk_api.handler.context` (removal in v4.0).

The handler surface lives in the ``atlan-application-sdk-api`` package so the
consolidated API host can serve an app's handler without this distribution.
Import from ``application_sdk_api.handler.context`` instead. Every name here resolves to the object
in the api package, so behaviour is unchanged; handler names warn.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING as _TYPE_CHECKING
from typing import Any as _Any

from application_sdk.handler.invocation import (  # noqa: F401 — not handler surface; not deprecated here
    bind_invocation_context,
)

if _TYPE_CHECKING:
    from application_sdk_api.handler.context import (  # noqa: F401
        APP_CONTEXT_ERROR,
        AppContextError,
        ErrorCode,
        HandlerContext,
        InternalError,
        PreconditionError,
        SecretStore,
        SecretStoreNotConfiguredError,
        bind_handler_context,
        get_handler_context,
        get_logger,
    )

#: Handler-surface names, served with a DeprecationWarning (removal in v4.0).
_DEPRECATED_CONSTANTS: dict[str, str] = {
    "APP_CONTEXT_ERROR": "application_sdk_api.handler.context.APP_CONTEXT_ERROR",
    "AppContextError": "application_sdk_api.handler.context.AppContextError",
    "ErrorCode": "application_sdk_api.handler.context.ErrorCode",
    "HandlerContext": "application_sdk_api.handler.context.HandlerContext",
    "InternalError": "application_sdk_api.handler.context.InternalError",
    "PreconditionError": "application_sdk_api.handler.context.PreconditionError",
    "SecretStore": "application_sdk_api.handler.context.SecretStore",
    "SecretStoreNotConfiguredError": "application_sdk_api.handler.context.SecretStoreNotConfiguredError",
    "bind_handler_context": "application_sdk_api.handler.context.bind_handler_context",
    "get_handler_context": "application_sdk_api.handler.context.get_handler_context",
    "get_logger": "application_sdk_api.handler.context.get_logger",
}

__all__ = [
    "APP_CONTEXT_ERROR",
    "AppContextError",
    "ErrorCode",
    "HandlerContext",
    "InternalError",
    "PreconditionError",
    "SecretStore",
    "SecretStoreNotConfiguredError",
    "bind_handler_context",
    "bind_invocation_context",
    "get_handler_context",
    "get_logger",
]


def __getattr__(name: str) -> _Any:
    target = _DEPRECATED_CONSTANTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, _, attr = target.rpartition(".")
    _warnings.warn(
        f"application_sdk.handler.context.{name} is deprecated and will be removed in v4.0; "
        f"import it from {module}",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
