"""Deprecated alias of :mod:`application_sdk_api.handler.manifest` (removal in v4.0).

The handler surface lives in the ``atlan-application-sdk-api`` package so the
consolidated API host can serve an app's handler without this distribution.
Import from ``application_sdk_api.handler.manifest`` instead. Every name here resolves to the object
in the api package, so behaviour is unchanged; handler names warn.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING as _TYPE_CHECKING
from typing import Any as _Any

if _TYPE_CHECKING:
    from application_sdk_api.handler.manifest import (  # noqa: F401
        AppManifest,
        DagNode,
        DagNodeDependency,
        ExecuteWorkflowInputs,
    )

#: Handler-surface names, served with a DeprecationWarning (removal in v4.0).
_DEPRECATED_CONSTANTS: dict[str, str] = {
    "AppManifest": "application_sdk_api.handler.manifest.AppManifest",
    "DagNode": "application_sdk_api.handler.manifest.DagNode",
    "DagNodeDependency": "application_sdk_api.handler.manifest.DagNodeDependency",
    "ExecuteWorkflowInputs": "application_sdk_api.handler.manifest.ExecuteWorkflowInputs",
}

__all__ = [
    "AppManifest",
    "DagNode",
    "DagNodeDependency",
    "ExecuteWorkflowInputs",
]


def __getattr__(name: str) -> _Any:
    target = _DEPRECATED_CONSTANTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, _, attr = target.rpartition(".")
    _warnings.warn(
        f"application_sdk.handler.manifest.{name} is deprecated and will be removed in v4.0; "
        f"import it from {module}",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
