"""Re-export of :mod:`application_sdk_api.errors.base`.

This code lives in the ``atlan-application-sdk-api`` package so the consolidated
API host and the worker share one implementation. ``application_sdk.errors.base`` is the
SDK's first-class path to the same objects and is not deprecated.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

from typing import Any as _Any

import application_sdk_api.errors.base as _src
from application_sdk_api.errors.base import (  # noqa: F401 — re-exported, same objects
    AppError,
    Audience,
    FailureCategory,
    redact_and_cap,
    redact_secrets,
    redact_wire_value,
    safe_traceback,
    sanitize_cause_repr,
)

__all__ = [
    "AppError",
    "Audience",
    "FailureCategory",
    "redact_and_cap",
    "redact_secrets",
    "redact_wire_value",
    "safe_traceback",
    "sanitize_cause_repr",
]


def __getattr__(name: str) -> _Any:
    # Private names are not re-exported above; resolve them from the source.
    return getattr(_src, name)
