"""Re-export of :mod:`application_sdk_api.errors.leaves`.

This code lives in the ``atlan-application-sdk-api`` package so the consolidated
API host and the worker share one implementation. ``application_sdk.errors.leaves`` is the
SDK's first-class path to the same objects and is not deprecated.

Generated by ``.github/scripts/gen_api_shims.py`` — do not edit. Make changes in
``packages/api`` and regenerate; ``guard_api_shims.py`` fails CI on hand edits.
"""

from __future__ import annotations

from typing import Any as _Any

import application_sdk_api.errors.leaves as _src
from application_sdk_api.errors.leaves import (  # noqa: F401 — re-exported, same objects
    WORKER_EVICTED_TYPE,
    AlreadyExistsError,
    AppError,
    AppPermissionDeniedError,
    AppTimeoutError,
    Audience,
    AuthError,
    CancelledError,
    ColdStartRaceError,
    DaprSidecarUnreachableError,
    DataIntegrityError,
    DependencyUnavailableError,
    DiskFullError,
    FailureCategory,
    InternalError,
    InvalidInputError,
    InvalidInputValueError,
    LocalVolumeUnwritableError,
    NotFoundError,
    ObjectStoreDownloadError,
    ObjectStoreReadError,
    PreconditionError,
    RateLimitedError,
    ResourceExhaustedError,
    SourceUnavailableError,
    TaskStalledError,
    UnimplementedError,
)

__all__ = [
    "AlreadyExistsError",
    "AppError",
    "AppPermissionDeniedError",
    "AppTimeoutError",
    "Audience",
    "AuthError",
    "CancelledError",
    "ColdStartRaceError",
    "DaprSidecarUnreachableError",
    "DataIntegrityError",
    "DependencyUnavailableError",
    "DiskFullError",
    "FailureCategory",
    "InternalError",
    "InvalidInputError",
    "InvalidInputValueError",
    "LocalVolumeUnwritableError",
    "NotFoundError",
    "ObjectStoreDownloadError",
    "ObjectStoreReadError",
    "PreconditionError",
    "RateLimitedError",
    "ResourceExhaustedError",
    "SourceUnavailableError",
    "TaskStalledError",
    "UnimplementedError",
    "WORKER_EVICTED_TYPE",
]


def __getattr__(name: str) -> _Any:
    # Private names are not re-exported above; resolve them from the source.
    return getattr(_src, name)
