# Pre-commit-checks. This can be reused across all the applications.

name: Pre-commit Checks
on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, labeled, reopened ]
    branches: [ main, master, develop ]

jobs:
  pre-commit:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.5
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-root --without dev,test --extras "workflows"
    - uses: pre-commit/action@v3.0.1
    - uses: webiny/action-conventional-commits@v1.3.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
