# Pre-commit-checks. This can be reused across all the applications.

name: Pre-commit Checks
on:
  workflow_call:
  push:
  pull_request:
    types: [ opened, synchronize, labeled, reopened ]

jobs:
  pre-commit:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-root --without dev,test --extras "workflows dashboard"
    - uses: pre-commit/action@v3.0.1