name: "Conformance"

on:
  pull_request: {}
  merge_group: {}
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  suite:
    uses: ./.github/workflows/conformance-reusable.yaml
    with:
      conformance-ref: ${{ github.event.pull_request.head.sha || github.sha }}
      exclude-paths-e: "tools/,contract-toolkit/"
      event_name: ${{ github.event_name }}
