name: Docs Verification and Generation for Apps

on:
  workflow_call:
    secrets:
      ORG_PAT_GITHUB:
        required: true

jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.ORG_PAT_GITHUB }}@github.com/".insteadOf "git@github.com:"
          poetry install -vv
          poetry add mkdocs mkdocs-material

      - name: Verify and Generate Docs
        run: |
          # Create Python script inline
          cat << 'EOF' > docs.py
          from application_sdk.docgen import AtlanDocsGenerator

          def main():
            docs_generator = AtlanDocsGenerator(
                docs_directory_path="docs",
                export_path="dist",
            )
            docs_generator.verify()
            docs_generator.export()

          if __name__ == "__main__":
            main()

          EOF

          poetry run python docs.py
