name: Build Docs and Push to Kryptonite

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: get_branch
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Install graphviz
        run: |
          sudo apt install graphviz
      - name: Generate Sphinx Docs
        run: |
          export POETRY_VIRTUALENVS_IN_PROJECT=1
          export POETRY_VIRTUALENVS_CREATE=1
          git config --global url."https://${{ secrets.ORG_PAT_GITHUB }}".insteadOf "ssh://git";
          poetry install
          source .venv/bin/activate
          make sphinx_docs
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::733936409301:role/kryptonite-store_FullAccess
      - name: Upload Docs to Kryptonite Bucket
        if: ${{ github.event_name == 'push' }}
        run: |
          aws s3 sync ./docs/_build/html s3://kryptonite-store/application-sdk --delete