name: Docstring Coverage

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
        description: 'Python package name to check docstring coverage'
        default: 'application_sdk'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - develop

jobs:
  docstring-coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install interrogate
        run: pip install interrogate

      - name: Create Coverage Report Header
        run: |
          echo "### 📜 Docstring Coverage Report" > docstring-cov.md
          echo >> docstring-cov.md

      - name: Run Basic Coverage Check
        run: |
          interrogate ${{ inputs.package_name }} --fail-under 10 >> docstring-cov.md

      - name: Add Detailed Report Section
        run: |
          echo >> docstring-cov.md
          echo >> docstring-cov.md
          echo "<details><summary>Detailed Coverage Report</summary>" >> docstring-cov.md
          echo >> docstring-cov.md
          echo "\`\`\`" >> docstring-cov.md

      - name: Run Detailed Coverage Check
        run: |
          interrogate ${{ inputs.package_name }} --fail-under 10 -v >> docstring-cov.md

      - name: Close Detailed Report Section
        run: |
          echo "\`\`\`" >> docstring-cov.md
          echo "</details>" >> docstring-cov.md

      - name: Comment Docstring Coverage on PR
        uses: mshick/add-pr-comment@v2
        with:
          message-id: "docstring-coverage"
          message-path: docstring-cov.md
