# Trivy container scan. This can be reused across all the applications.

name: E2E Test for Application Examples
on:
  workflow_call:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    # workflow setup
    - name: Install Dapr CLI
      uses: ./.github/actions/workflow-setup 

    # Make API call and capture workflow/run IDs for each example
    - name: Start the workflows
      id: workflow_info
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SNOWFLAKE_ACCOUNT_ID: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        cd examples
        poetry run python run_examples.py

        echo "Workflow status:"
        cat workflow_status.md

     # workflow status validation

    - name: Validate workflow status
      uses: ./.github/actions/workflow-status