name: On-Push Checks

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  security-events: write
  actions: write

jobs:
  # Testing
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/unit-tests"
        with:
          github-token: ${{ secrets.ORG_PAT_GITHUB }}
          fail-under: "60"

  e2e-examples:
    name: E2E (Examples)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/e2e-examples"
        with:
          github-token: ${{ secrets.ORG_PAT_GITHUB }}
          postgres-host: ${{ secrets.POSTGRES_HOST }}
          postgres-password: ${{ secrets.POSTGRES_PASSWORD }}
          snowflake-account-id: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          snowflake-user: ${{ secrets.SNOWFLAKE_USER }}
          snowflake-password: ${{ secrets.SNOWFLAKE_PASSWORD }}

  e2e-apps:
    name: E2E (Apps)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name: ["atlan-postgres-app"]
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/e2e-apps"
        with:
          github-token: ${{ secrets.ORG_PAT_GITHUB }}
          repo-name: ${{ matrix.repo_name }}

  # Documentation
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-deps"
      - name: Install graphviz
        run: |
          sudo apt install graphviz
      - name: Generate Sphinx Docs and UML Diagrams
        run: |
          source .venv/bin/activate
          make apidocs
      - name: Upload Docs
        uses: atlanhq/kryptonite/upload@v1
        with:
          source: ./docs/site
          target: application-sdk/${{ github.head_ref }}
      - name: Comment Kryptonite URL on PR
        uses: mshick/add-pr-comment@v2
        with:
          message-id: "docs"
          message: |
            🛠 Docs available at: https://k.atlan.dev/application-sdk/${{ github.head_ref }}