# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    branches: [main, develop]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  security-events: write
  actions: write

permissions:
  contents: read
  pull-requests: write
  actions: read
  security-events: write

jobs:
  # Security Checks
  trivy:
    name: Trivy Code Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/trivy"
        with:
          add-report-comment-to-pr: "true"