name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Run Tests with Coverage
        run: |
          poetry install
          poetry run coverage run -m pytest tests/unit
          poetry run coverage xml
          poetry run coverage report

      - name: Comment Coverage Report on PR
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
