name: Validate PR Title
run-name: ${{ github.actor }} is ensuring Jira ID is present in PR title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, develop]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'develop' && github.event.pull_request.head.ref != 'master' }}
    steps:
      - name: Enforce Pull Request Title includes Jira Issue Key
        uses: ryanvade/enforce-pr-title-style-action@v2.1.1
        with:
          keyAnywhereInTitle: 'true'
      - name: Enforce Pull Request Title follows semantic commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

