# Validate Pull Request Title
#
# This action validates pull request titles in two ways:
# Ensures a Jira issue key (e.g., ABC-123) is present anywhere in the PR title, and if the
# PR title match the Conventional Commits spec.
#
# Examples:
#   - "feat: APP-3214 Add user authentication"
#   - "fix: APP-1234 Resolve memory leak issue"

name: Validate PR Title
run-name: ${{ github.actor }} is ensuring Jira ID is present in PR title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, develop]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'develop' && github.event.pull_request.head.ref != 'master' }}
    steps:
      - name: Enforce Pull Request Title includes Jira Issue Key
        uses: ryanvade/enforce-pr-title-style-action@v2.1.2
        with:
          keyAnywhereInTitle: 'true'
      - name: Enforce Pull Request Title follows semantic commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

